// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: archive.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const claimArchiveImportOperation = `-- name: ClaimArchiveImportOperation :one
WITH expired AS (
  DELETE FROM archive_import_operations
  WHERE id IN (
    SELECT id
    FROM archive_import_operations
    WHERE status IN ('completed', 'failed')
      AND COALESCE(completed_at, created_at) < now() - interval '30 days'
    ORDER BY COALESCE(completed_at, created_at)
    LIMIT 1000
  )
)
INSERT INTO archive_import_operations (
  id, user_id, archive_hash, status, lease_until, claim_token
)
VALUES (
  $1::uuid,
  $2::uuid,
  $3::text,
  'processing',
  now() + interval '2 hours',
  $4::uuid
)
ON CONFLICT (id) DO UPDATE
SET status = 'processing',
    lease_until = now() + interval '2 hours',
    claim_token = excluded.claim_token,
    last_error = NULL
WHERE archive_import_operations.user_id = excluded.user_id
  AND archive_import_operations.archive_hash = excluded.archive_hash
  AND (
    archive_import_operations.status = 'failed'
    OR (
      archive_import_operations.status = 'processing'
      AND archive_import_operations.lease_until <= now()
    )
  )
RETURNING id, user_id, archive_hash, claim_token, status, lease_until, id_map, result, last_error, created_at, completed_at
`

type ClaimArchiveImportOperationParams struct {
	ID          uuid.UUID `json:"id"`
	UserID      uuid.UUID `json:"user_id"`
	ArchiveHash string    `json:"archive_hash"`
	ClaimToken  uuid.UUID `json:"claim_token"`
}

func (q *Queries) ClaimArchiveImportOperation(ctx context.Context, arg ClaimArchiveImportOperationParams) (ArchiveImportOperation, error) {
	row := q.db.QueryRow(ctx, claimArchiveImportOperation,
		arg.ID,
		arg.UserID,
		arg.ArchiveHash,
		arg.ClaimToken,
	)
	var i ArchiveImportOperation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ArchiveHash,
		&i.ClaimToken,
		&i.Status,
		&i.LeaseUntil,
		&i.IDMap,
		&i.Result,
		&i.LastError,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const completeArchiveImportOperation = `-- name: CompleteArchiveImportOperation :execrows
UPDATE archive_import_operations
SET status = 'completed',
    lease_until = now(),
    id_map = $1::jsonb,
    result = $2::jsonb,
    completed_at = now(),
    last_error = NULL
WHERE id = $3::uuid
  AND user_id = $4::uuid
  AND archive_hash = $5::text
  AND claim_token = $6::uuid
  AND status = 'processing'
`

type CompleteArchiveImportOperationParams struct {
	IDMap       []byte    `json:"id_map"`
	Result      []byte    `json:"result"`
	ID          uuid.UUID `json:"id"`
	UserID      uuid.UUID `json:"user_id"`
	ArchiveHash string    `json:"archive_hash"`
	ClaimToken  uuid.UUID `json:"claim_token"`
}

func (q *Queries) CompleteArchiveImportOperation(ctx context.Context, arg CompleteArchiveImportOperationParams) (int64, error) {
	result, err := q.db.Exec(ctx, completeArchiveImportOperation,
		arg.IDMap,
		arg.Result,
		arg.ID,
		arg.UserID,
		arg.ArchiveHash,
		arg.ClaimToken,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const failArchiveImportOperation = `-- name: FailArchiveImportOperation :execrows
UPDATE archive_import_operations
SET status = 'failed',
    lease_until = now(),
    last_error = $1::text
WHERE id = $2::uuid
  AND user_id = $3::uuid
  AND archive_hash = $4::text
  AND claim_token = $5::uuid
  AND status = 'processing'
`

type FailArchiveImportOperationParams struct {
	LastError   string    `json:"last_error"`
	ID          uuid.UUID `json:"id"`
	UserID      uuid.UUID `json:"user_id"`
	ArchiveHash string    `json:"archive_hash"`
	ClaimToken  uuid.UUID `json:"claim_token"`
}

func (q *Queries) FailArchiveImportOperation(ctx context.Context, arg FailArchiveImportOperationParams) (int64, error) {
	result, err := q.db.Exec(ctx, failArchiveImportOperation,
		arg.LastError,
		arg.ID,
		arg.UserID,
		arg.ArchiveHash,
		arg.ClaimToken,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getArchiveCapturePairState = `-- name: GetArchiveCapturePairState :one
SELECT
  (
    SELECT created_at FROM capture_links
    WHERE user_id = $1::uuid
      AND a_id = LEAST($2::uuid, $3::uuid)
      AND b_id = GREATEST($2::uuid, $3::uuid)
  )::timestamptz AS link_created_at,
  (
    SELECT max(created_at) FROM retrieval_dismissals
    WHERE user_id = $1::uuid
      AND surface = 'related'
      AND (
        (anchor_id = $2::uuid AND target_id = $3::uuid)
        OR (anchor_id = $3::uuid AND target_id = $2::uuid)
      )
  )::timestamptz AS dismissal_created_at
`

type GetArchiveCapturePairStateParams struct {
	UserID uuid.UUID `json:"user_id"`
	X      uuid.UUID `json:"x"`
	Y      uuid.UUID `json:"y"`
}

type GetArchiveCapturePairStateRow struct {
	LinkCreatedAt      pgtype.Timestamptz `json:"link_created_at"`
	DismissalCreatedAt pgtype.Timestamptz `json:"dismissal_created_at"`
}

func (q *Queries) GetArchiveCapturePairState(ctx context.Context, arg GetArchiveCapturePairStateParams) (GetArchiveCapturePairStateRow, error) {
	row := q.db.QueryRow(ctx, getArchiveCapturePairState, arg.UserID, arg.X, arg.Y)
	var i GetArchiveCapturePairStateRow
	err := row.Scan(&i.LinkCreatedAt, &i.DismissalCreatedAt)
	return i, err
}

const getArchiveImportOperation = `-- name: GetArchiveImportOperation :one
SELECT id, user_id, archive_hash, claim_token, status, lease_until, id_map, result, last_error, created_at, completed_at FROM archive_import_operations
WHERE id = $1::uuid
`

func (q *Queries) GetArchiveImportOperation(ctx context.Context, id uuid.UUID) (ArchiveImportOperation, error) {
	row := q.db.QueryRow(ctx, getArchiveImportOperation, id)
	var i ArchiveImportOperation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ArchiveHash,
		&i.ClaimToken,
		&i.Status,
		&i.LeaseUntil,
		&i.IDMap,
		&i.Result,
		&i.LastError,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getCaptureOwner = `-- name: GetCaptureOwner :one
SELECT id, user_id FROM captures
WHERE id = $1::uuid
`

type GetCaptureOwnerRow struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetCaptureOwner(ctx context.Context, id uuid.UUID) (GetCaptureOwnerRow, error) {
	row := q.db.QueryRow(ctx, getCaptureOwner, id)
	var i GetCaptureOwnerRow
	err := row.Scan(&i.ID, &i.UserID)
	return i, err
}

const insertArchiveCapture = `-- name: InsertArchiveCapture :one
INSERT INTO captures (
  id, user_id, raw_text, media_url, media_type, classified_as, created_at,
  source, transcript, transcription_status, transcription_model,
  transcription_attempts, transcribed_at, next_transcription_at,
  audio_duration_sec, media_key, remind_at, deleted_at, remind_hide,
  todo_at, done_at, link_url
)
VALUES (
  $1::uuid,
  $2::uuid,
  $3::text,
  $4::text,
  $5::capture_media_type,
  $6::capture_classified_as,
  $7::timestamptz,
  $8::text,
  $9::text,
  $10::transcription_status,
  $11::text,
  $12::integer,
  $13::timestamptz,
  $14::timestamptz,
  $15::integer,
  $16::text,
  $17::timestamptz,
  $18::timestamptz,
  $19::boolean,
  $20::timestamptz,
  $21::timestamptz,
  $22::text
)
ON CONFLICT (id) DO NOTHING
RETURNING id, user_id, raw_text, media_url, media_type, classified_as, task_id, created_at, source, transcript, transcription_status, transcription_model, transcription_attempts, transcribed_at, next_transcription_at, audio_duration_sec, media_key, remind_at, deleted_at, remind_hide, todo_at, done_at, link_url
`

type InsertArchiveCaptureParams struct {
	ID                    uuid.UUID           `json:"id"`
	UserID                uuid.UUID           `json:"user_id"`
	RawText               pgtype.Text         `json:"raw_text"`
	MediaUrl              pgtype.Text         `json:"media_url"`
	MediaType             CaptureMediaType    `json:"media_type"`
	ClassifiedAs          CaptureClassifiedAs `json:"classified_as"`
	CreatedAt             pgtype.Timestamptz  `json:"created_at"`
	Source                string              `json:"source"`
	Transcript            pgtype.Text         `json:"transcript"`
	TranscriptionStatus   TranscriptionStatus `json:"transcription_status"`
	TranscriptionModel    pgtype.Text         `json:"transcription_model"`
	TranscriptionAttempts int32               `json:"transcription_attempts"`
	TranscribedAt         pgtype.Timestamptz  `json:"transcribed_at"`
	NextTranscriptionAt   pgtype.Timestamptz  `json:"next_transcription_at"`
	AudioDurationSec      pgtype.Int4         `json:"audio_duration_sec"`
	MediaKey              pgtype.Text         `json:"media_key"`
	RemindAt              pgtype.Timestamptz  `json:"remind_at"`
	DeletedAt             pgtype.Timestamptz  `json:"deleted_at"`
	RemindHide            bool                `json:"remind_hide"`
	TodoAt                pgtype.Timestamptz  `json:"todo_at"`
	DoneAt                pgtype.Timestamptz  `json:"done_at"`
	LinkUrl               pgtype.Text         `json:"link_url"`
}

func (q *Queries) InsertArchiveCapture(ctx context.Context, arg InsertArchiveCaptureParams) (Capture, error) {
	row := q.db.QueryRow(ctx, insertArchiveCapture,
		arg.ID,
		arg.UserID,
		arg.RawText,
		arg.MediaUrl,
		arg.MediaType,
		arg.ClassifiedAs,
		arg.CreatedAt,
		arg.Source,
		arg.Transcript,
		arg.TranscriptionStatus,
		arg.TranscriptionModel,
		arg.TranscriptionAttempts,
		arg.TranscribedAt,
		arg.NextTranscriptionAt,
		arg.AudioDurationSec,
		arg.MediaKey,
		arg.RemindAt,
		arg.DeletedAt,
		arg.RemindHide,
		arg.TodoAt,
		arg.DoneAt,
		arg.LinkUrl,
	)
	var i Capture
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RawText,
		&i.MediaUrl,
		&i.MediaType,
		&i.ClassifiedAs,
		&i.TaskID,
		&i.CreatedAt,
		&i.Source,
		&i.Transcript,
		&i.TranscriptionStatus,
		&i.TranscriptionModel,
		&i.TranscriptionAttempts,
		&i.TranscribedAt,
		&i.NextTranscriptionAt,
		&i.AudioDurationSec,
		&i.MediaKey,
		&i.RemindAt,
		&i.DeletedAt,
		&i.RemindHide,
		&i.TodoAt,
		&i.DoneAt,
		&i.LinkUrl,
	)
	return i, err
}

const insertArchiveCaptureAttachment = `-- name: InsertArchiveCaptureAttachment :one
INSERT INTO capture_attachments (
  id, user_id, capture_id, provider, provider_file_id, name, mime_type,
  size_bytes, web_url, created_at, deleted_at
)
VALUES (
  $1::uuid,
  $2::uuid,
  $3::uuid,
  $4::cloud_drive_provider,
  $5::text,
  $6::text,
  $7::text,
  $8::bigint,
  $9::text,
  $10::timestamptz,
  $11::timestamptz
)
ON CONFLICT DO NOTHING
RETURNING id, user_id, capture_id, provider, provider_file_id, name, mime_type, size_bytes, web_url, created_at, deleted_at
`

type InsertArchiveCaptureAttachmentParams struct {
	ID             uuid.UUID          `json:"id"`
	UserID         uuid.UUID          `json:"user_id"`
	CaptureID      uuid.UUID          `json:"capture_id"`
	Provider       CloudDriveProvider `json:"provider"`
	ProviderFileID string             `json:"provider_file_id"`
	Name           string             `json:"name"`
	MimeType       pgtype.Text        `json:"mime_type"`
	SizeBytes      pgtype.Int8        `json:"size_bytes"`
	WebUrl         string             `json:"web_url"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	DeletedAt      pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) InsertArchiveCaptureAttachment(ctx context.Context, arg InsertArchiveCaptureAttachmentParams) (CaptureAttachment, error) {
	row := q.db.QueryRow(ctx, insertArchiveCaptureAttachment,
		arg.ID,
		arg.UserID,
		arg.CaptureID,
		arg.Provider,
		arg.ProviderFileID,
		arg.Name,
		arg.MimeType,
		arg.SizeBytes,
		arg.WebUrl,
		arg.CreatedAt,
		arg.DeletedAt,
	)
	var i CaptureAttachment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CaptureID,
		&i.Provider,
		&i.ProviderFileID,
		&i.Name,
		&i.MimeType,
		&i.SizeBytes,
		&i.WebUrl,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const insertArchiveCaptureLink = `-- name: InsertArchiveCaptureLink :one
INSERT INTO capture_links (a_id, b_id, user_id, created_at)
VALUES (
  LEAST($1::uuid, $2::uuid),
  GREATEST($1::uuid, $2::uuid),
  $3::uuid,
  $4::timestamptz
)
ON CONFLICT (a_id, b_id) DO UPDATE
SET created_at = GREATEST(capture_links.created_at, EXCLUDED.created_at)
RETURNING a_id, b_id, user_id, created_at
`

type InsertArchiveCaptureLinkParams struct {
	X         uuid.UUID          `json:"x"`
	Y         uuid.UUID          `json:"y"`
	UserID    uuid.UUID          `json:"user_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) InsertArchiveCaptureLink(ctx context.Context, arg InsertArchiveCaptureLinkParams) (CaptureLink, error) {
	row := q.db.QueryRow(ctx, insertArchiveCaptureLink,
		arg.X,
		arg.Y,
		arg.UserID,
		arg.CreatedAt,
	)
	var i CaptureLink
	err := row.Scan(
		&i.AID,
		&i.BID,
		&i.UserID,
		&i.CreatedAt,
	)
	return i, err
}

const insertArchiveRelatedDismissal = `-- name: InsertArchiveRelatedDismissal :execrows
INSERT INTO retrieval_dismissals (
  user_id, surface, anchor_id, target_id, created_at
)
SELECT
  $1::uuid, 'related', $2::uuid,
  $3::uuid, $4::timestamptz
WHERE EXISTS (
  SELECT 1 FROM captures
  WHERE id = $2::uuid AND user_id = $1::uuid
)
AND EXISTS (
  SELECT 1 FROM captures
  WHERE id = $3::uuid AND user_id = $1::uuid
)
ON CONFLICT (user_id, anchor_id, target_id) WHERE surface = 'related'
DO UPDATE SET created_at = GREATEST(retrieval_dismissals.created_at, EXCLUDED.created_at)
`

type InsertArchiveRelatedDismissalParams struct {
	UserID    uuid.UUID          `json:"user_id"`
	AnchorID  uuid.UUID          `json:"anchor_id"`
	TargetID  uuid.UUID          `json:"target_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) InsertArchiveRelatedDismissal(ctx context.Context, arg InsertArchiveRelatedDismissalParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertArchiveRelatedDismissal,
		arg.UserID,
		arg.AnchorID,
		arg.TargetID,
		arg.CreatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertArchiveRelatedDismissalPair = `-- name: InsertArchiveRelatedDismissalPair :execrows
INSERT INTO retrieval_dismissals (
  user_id, surface, anchor_id, target_id, created_at
)
SELECT
  $1::uuid, 'related', pair.anchor_id, pair.target_id,
  $2::timestamptz
FROM (
  VALUES
    ($3::uuid, $4::uuid),
    ($4::uuid, $3::uuid)
) AS pair(anchor_id, target_id)
WHERE EXISTS (
  SELECT 1 FROM captures
  WHERE id = pair.anchor_id AND user_id = $1::uuid
)
AND EXISTS (
  SELECT 1 FROM captures
  WHERE id = pair.target_id AND user_id = $1::uuid
)
ON CONFLICT (user_id, anchor_id, target_id) WHERE surface = 'related'
DO UPDATE SET created_at = GREATEST(retrieval_dismissals.created_at, EXCLUDED.created_at)
`

type InsertArchiveRelatedDismissalPairParams struct {
	UserID    uuid.UUID          `json:"user_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	X         uuid.UUID          `json:"x"`
	Y         uuid.UUID          `json:"y"`
}

func (q *Queries) InsertArchiveRelatedDismissalPair(ctx context.Context, arg InsertArchiveRelatedDismissalPairParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertArchiveRelatedDismissalPair,
		arg.UserID,
		arg.CreatedAt,
		arg.X,
		arg.Y,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertArchiveSearchDismissal = `-- name: InsertArchiveSearchDismissal :execrows
INSERT INTO retrieval_dismissals (
  user_id, surface, query_hash, query_text, target_id, created_at
)
SELECT
  $1::uuid, 'search', $2,
  $3::text, $4::uuid,
  $5::timestamptz
WHERE EXISTS (
  SELECT 1 FROM captures
  WHERE id = $4::uuid AND user_id = $1::uuid
)
ON CONFLICT (user_id, query_hash, target_id) WHERE surface = 'search'
DO UPDATE SET
  query_text = EXCLUDED.query_text,
  created_at = GREATEST(retrieval_dismissals.created_at, EXCLUDED.created_at)
`

type InsertArchiveSearchDismissalParams struct {
	UserID    uuid.UUID          `json:"user_id"`
	QueryHash []byte             `json:"query_hash"`
	QueryText string             `json:"query_text"`
	TargetID  uuid.UUID          `json:"target_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) InsertArchiveSearchDismissal(ctx context.Context, arg InsertArchiveSearchDismissalParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertArchiveSearchDismissal,
		arg.UserID,
		arg.QueryHash,
		arg.QueryText,
		arg.TargetID,
		arg.CreatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listArchiveCaptureAttachments = `-- name: ListArchiveCaptureAttachments :many
SELECT id, user_id, capture_id, provider, provider_file_id, name, mime_type, size_bytes, web_url, created_at, deleted_at FROM capture_attachments
WHERE user_id = $1
ORDER BY created_at, id
`

func (q *Queries) ListArchiveCaptureAttachments(ctx context.Context, userID uuid.UUID) ([]CaptureAttachment, error) {
	rows, err := q.db.Query(ctx, listArchiveCaptureAttachments, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CaptureAttachment
	for rows.Next() {
		var i CaptureAttachment
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CaptureID,
			&i.Provider,
			&i.ProviderFileID,
			&i.Name,
			&i.MimeType,
			&i.SizeBytes,
			&i.WebUrl,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArchiveCaptureAttachmentsPage = `-- name: ListArchiveCaptureAttachmentsPage :many
SELECT id, user_id, capture_id, provider, provider_file_id, name, mime_type, size_bytes, web_url, created_at, deleted_at FROM capture_attachments
WHERE user_id = $1
  AND (
    $2::timestamptz IS NULL
    OR (created_at, id) > (
      $2::timestamptz,
      $3::uuid
    )
  )
ORDER BY created_at, id
LIMIT $4
`

type ListArchiveCaptureAttachmentsPageParams struct {
	UserID         uuid.UUID          `json:"user_id"`
	AfterCreatedAt pgtype.Timestamptz `json:"after_created_at"`
	AfterID        uuid.UUID          `json:"after_id"`
	PageSize       int32              `json:"page_size"`
}

func (q *Queries) ListArchiveCaptureAttachmentsPage(ctx context.Context, arg ListArchiveCaptureAttachmentsPageParams) ([]CaptureAttachment, error) {
	rows, err := q.db.Query(ctx, listArchiveCaptureAttachmentsPage,
		arg.UserID,
		arg.AfterCreatedAt,
		arg.AfterID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CaptureAttachment
	for rows.Next() {
		var i CaptureAttachment
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CaptureID,
			&i.Provider,
			&i.ProviderFileID,
			&i.Name,
			&i.MimeType,
			&i.SizeBytes,
			&i.WebUrl,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArchiveCaptureLinks = `-- name: ListArchiveCaptureLinks :many
SELECT a_id, b_id, user_id, created_at FROM capture_links
WHERE user_id = $1
ORDER BY created_at, a_id, b_id
`

func (q *Queries) ListArchiveCaptureLinks(ctx context.Context, userID uuid.UUID) ([]CaptureLink, error) {
	rows, err := q.db.Query(ctx, listArchiveCaptureLinks, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CaptureLink
	for rows.Next() {
		var i CaptureLink
		if err := rows.Scan(
			&i.AID,
			&i.BID,
			&i.UserID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArchiveCaptureLinksPage = `-- name: ListArchiveCaptureLinksPage :many
SELECT a_id, b_id, user_id, created_at FROM capture_links
WHERE user_id = $1
  AND (
    $2::timestamptz IS NULL
    OR (created_at, a_id, b_id) > (
      $2::timestamptz,
      $3::uuid,
      $4::uuid
    )
  )
ORDER BY created_at, a_id, b_id
LIMIT $5
`

type ListArchiveCaptureLinksPageParams struct {
	UserID         uuid.UUID          `json:"user_id"`
	AfterCreatedAt pgtype.Timestamptz `json:"after_created_at"`
	AfterAID       uuid.UUID          `json:"after_a_id"`
	AfterBID       uuid.UUID          `json:"after_b_id"`
	PageSize       int32              `json:"page_size"`
}

func (q *Queries) ListArchiveCaptureLinksPage(ctx context.Context, arg ListArchiveCaptureLinksPageParams) ([]CaptureLink, error) {
	rows, err := q.db.Query(ctx, listArchiveCaptureLinksPage,
		arg.UserID,
		arg.AfterCreatedAt,
		arg.AfterAID,
		arg.AfterBID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CaptureLink
	for rows.Next() {
		var i CaptureLink
		if err := rows.Scan(
			&i.AID,
			&i.BID,
			&i.UserID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArchiveCaptures = `-- name: ListArchiveCaptures :many
SELECT id, user_id, raw_text, media_url, media_type, classified_as, task_id, created_at, source, transcript, transcription_status, transcription_model, transcription_attempts, transcribed_at, next_transcription_at, audio_duration_sec, media_key, remind_at, deleted_at, remind_hide, todo_at, done_at, link_url FROM captures
WHERE user_id = $1
ORDER BY created_at, id
`

func (q *Queries) ListArchiveCaptures(ctx context.Context, userID uuid.UUID) ([]Capture, error) {
	rows, err := q.db.Query(ctx, listArchiveCaptures, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Capture
	for rows.Next() {
		var i Capture
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.RawText,
			&i.MediaUrl,
			&i.MediaType,
			&i.ClassifiedAs,
			&i.TaskID,
			&i.CreatedAt,
			&i.Source,
			&i.Transcript,
			&i.TranscriptionStatus,
			&i.TranscriptionModel,
			&i.TranscriptionAttempts,
			&i.TranscribedAt,
			&i.NextTranscriptionAt,
			&i.AudioDurationSec,
			&i.MediaKey,
			&i.RemindAt,
			&i.DeletedAt,
			&i.RemindHide,
			&i.TodoAt,
			&i.DoneAt,
			&i.LinkUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArchiveCapturesPage = `-- name: ListArchiveCapturesPage :many
SELECT id, user_id, raw_text, media_url, media_type, classified_as, task_id, created_at, source, transcript, transcription_status, transcription_model, transcription_attempts, transcribed_at, next_transcription_at, audio_duration_sec, media_key, remind_at, deleted_at, remind_hide, todo_at, done_at, link_url FROM captures
WHERE user_id = $1
  AND (
    $2::timestamptz IS NULL
    OR (created_at, id) > (
      $2::timestamptz,
      $3::uuid
    )
  )
ORDER BY created_at, id
LIMIT $4
`

type ListArchiveCapturesPageParams struct {
	UserID         uuid.UUID          `json:"user_id"`
	AfterCreatedAt pgtype.Timestamptz `json:"after_created_at"`
	AfterID        uuid.UUID          `json:"after_id"`
	PageSize       int32              `json:"page_size"`
}

func (q *Queries) ListArchiveCapturesPage(ctx context.Context, arg ListArchiveCapturesPageParams) ([]Capture, error) {
	rows, err := q.db.Query(ctx, listArchiveCapturesPage,
		arg.UserID,
		arg.AfterCreatedAt,
		arg.AfterID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Capture
	for rows.Next() {
		var i Capture
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.RawText,
			&i.MediaUrl,
			&i.MediaType,
			&i.ClassifiedAs,
			&i.TaskID,
			&i.CreatedAt,
			&i.Source,
			&i.Transcript,
			&i.TranscriptionStatus,
			&i.TranscriptionModel,
			&i.TranscriptionAttempts,
			&i.TranscribedAt,
			&i.NextTranscriptionAt,
			&i.AudioDurationSec,
			&i.MediaKey,
			&i.RemindAt,
			&i.DeletedAt,
			&i.RemindHide,
			&i.TodoAt,
			&i.DoneAt,
			&i.LinkUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArchiveRelatedDismissalsPage = `-- name: ListArchiveRelatedDismissalsPage :many
SELECT user_id, surface, query_hash, anchor_id, target_id, created_at, query_text FROM retrieval_dismissals
WHERE user_id = $1
  AND surface = 'related'
  AND (
    $2::timestamptz IS NULL
    OR (created_at, anchor_id, target_id) > (
      $2::timestamptz,
      $3::uuid,
      $4::uuid
    )
  )
ORDER BY created_at, anchor_id, target_id
LIMIT $5
`

type ListArchiveRelatedDismissalsPageParams struct {
	UserID         uuid.UUID          `json:"user_id"`
	AfterCreatedAt pgtype.Timestamptz `json:"after_created_at"`
	AfterAnchorID  uuid.UUID          `json:"after_anchor_id"`
	AfterTargetID  uuid.UUID          `json:"after_target_id"`
	PageSize       int32              `json:"page_size"`
}

func (q *Queries) ListArchiveRelatedDismissalsPage(ctx context.Context, arg ListArchiveRelatedDismissalsPageParams) ([]RetrievalDismissal, error) {
	rows, err := q.db.Query(ctx, listArchiveRelatedDismissalsPage,
		arg.UserID,
		arg.AfterCreatedAt,
		arg.AfterAnchorID,
		arg.AfterTargetID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RetrievalDismissal
	for rows.Next() {
		var i RetrievalDismissal
		if err := rows.Scan(
			&i.UserID,
			&i.Surface,
			&i.QueryHash,
			&i.AnchorID,
			&i.TargetID,
			&i.CreatedAt,
			&i.QueryText,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArchiveRetrievalDismissals = `-- name: ListArchiveRetrievalDismissals :many
SELECT user_id, surface, query_hash, anchor_id, target_id, created_at, query_text FROM retrieval_dismissals
WHERE user_id = $1
ORDER BY created_at, surface, query_hash, anchor_id, target_id
`

func (q *Queries) ListArchiveRetrievalDismissals(ctx context.Context, userID uuid.UUID) ([]RetrievalDismissal, error) {
	rows, err := q.db.Query(ctx, listArchiveRetrievalDismissals, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RetrievalDismissal
	for rows.Next() {
		var i RetrievalDismissal
		if err := rows.Scan(
			&i.UserID,
			&i.Surface,
			&i.QueryHash,
			&i.AnchorID,
			&i.TargetID,
			&i.CreatedAt,
			&i.QueryText,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArchiveSearchDismissalsPage = `-- name: ListArchiveSearchDismissalsPage :many
SELECT user_id, surface, query_hash, anchor_id, target_id, created_at, query_text FROM retrieval_dismissals
WHERE user_id = $1
  AND surface = 'search'
  AND (
    $2::timestamptz IS NULL
    OR (created_at, query_hash, target_id) > (
      $2::timestamptz,
      $3::bytea,
      $4::uuid
    )
  )
ORDER BY created_at, query_hash, target_id
LIMIT $5
`

type ListArchiveSearchDismissalsPageParams struct {
	UserID         uuid.UUID          `json:"user_id"`
	AfterCreatedAt pgtype.Timestamptz `json:"after_created_at"`
	AfterQueryHash []byte             `json:"after_query_hash"`
	AfterTargetID  uuid.UUID          `json:"after_target_id"`
	PageSize       int32              `json:"page_size"`
}

func (q *Queries) ListArchiveSearchDismissalsPage(ctx context.Context, arg ListArchiveSearchDismissalsPageParams) ([]RetrievalDismissal, error) {
	rows, err := q.db.Query(ctx, listArchiveSearchDismissalsPage,
		arg.UserID,
		arg.AfterCreatedAt,
		arg.AfterQueryHash,
		arg.AfterTargetID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RetrievalDismissal
	for rows.Next() {
		var i RetrievalDismissal
		if err := rows.Scan(
			&i.UserID,
			&i.Surface,
			&i.QueryHash,
			&i.AnchorID,
			&i.TargetID,
			&i.CreatedAt,
			&i.QueryText,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockArchiveImportCaptures = `-- name: LockArchiveImportCaptures :many
SELECT id FROM captures
WHERE user_id = $1::uuid
  AND id = ANY($2::uuid[])
ORDER BY id
FOR KEY SHARE
`

type LockArchiveImportCapturesParams struct {
	UserID     uuid.UUID   `json:"user_id"`
	CaptureIds []uuid.UUID `json:"capture_ids"`
}

// Canonical ordering prevents two imports from taking overlapping Capture row
// locks in opposite orders. Missing rows are new archive Captures and need no
// lock before they are inserted by this transaction.
func (q *Queries) LockArchiveImportCaptures(ctx context.Context, arg LockArchiveImportCapturesParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, lockArchiveImportCaptures, arg.UserID, arg.CaptureIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockArchiveImportUser = `-- name: LockArchiveImportUser :exec
SELECT id FROM users
WHERE id = $1::uuid
FOR KEY SHARE
`

// Lock parent rows before the archive retrieval guards. This keeps account
// deletion and its relationship cascades out of the reverse lock order.
func (q *Queries) LockArchiveImportUser(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, lockArchiveImportUser, userID)
	return err
}
