// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth_state.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearAuthRateLimit = `-- name: ClearAuthRateLimit :exec
DELETE FROM auth_rate_limits
WHERE scope = $1 AND subject_hash = $2
`

type ClearAuthRateLimitParams struct {
	Scope       string `json:"scope"`
	SubjectHash []byte `json:"subject_hash"`
}

func (q *Queries) ClearAuthRateLimit(ctx context.Context, arg ClearAuthRateLimitParams) error {
	_, err := q.db.Exec(ctx, clearAuthRateLimit, arg.Scope, arg.SubjectHash)
	return err
}

const consumeAuthEphemeralState = `-- name: ConsumeAuthEphemeralState :one
DELETE FROM auth_ephemeral_states
WHERE purpose = $1
  AND key_hash = $2
  AND expires_at > now()
RETURNING payload
`

type ConsumeAuthEphemeralStateParams struct {
	Purpose string `json:"purpose"`
	KeyHash []byte `json:"key_hash"`
}

func (q *Queries) ConsumeAuthEphemeralState(ctx context.Context, arg ConsumeAuthEphemeralStateParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, consumeAuthEphemeralState, arg.Purpose, arg.KeyHash)
	var payload []byte
	err := row.Scan(&payload)
	return payload, err
}

const consumeMatchingAuthEphemeralState = `-- name: ConsumeMatchingAuthEphemeralState :one
DELETE FROM auth_ephemeral_states
WHERE purpose = $1
  AND key_hash = $2
  AND payload = $3
  AND expires_at > now()
RETURNING payload
`

type ConsumeMatchingAuthEphemeralStateParams struct {
	Purpose string `json:"purpose"`
	KeyHash []byte `json:"key_hash"`
	Payload []byte `json:"payload"`
}

func (q *Queries) ConsumeMatchingAuthEphemeralState(ctx context.Context, arg ConsumeMatchingAuthEphemeralStateParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, consumeMatchingAuthEphemeralState, arg.Purpose, arg.KeyHash, arg.Payload)
	var payload []byte
	err := row.Scan(&payload)
	return payload, err
}

const getAuthEphemeralState = `-- name: GetAuthEphemeralState :one
SELECT payload
FROM auth_ephemeral_states
WHERE purpose = $1
  AND key_hash = $2
  AND expires_at > now()
`

type GetAuthEphemeralStateParams struct {
	Purpose string `json:"purpose"`
	KeyHash []byte `json:"key_hash"`
}

func (q *Queries) GetAuthEphemeralState(ctx context.Context, arg GetAuthEphemeralStateParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, getAuthEphemeralState, arg.Purpose, arg.KeyHash)
	var payload []byte
	err := row.Scan(&payload)
	return payload, err
}

const incrementAuthRateLimit = `-- name: IncrementAuthRateLimit :one
WITH expired AS (
  DELETE FROM auth_rate_limits
  WHERE (scope, subject_hash) IN (
    SELECT scope, subject_hash
    FROM auth_rate_limits
    WHERE expires_at <= now()
      AND NOT (scope = $1 AND subject_hash = $2)
    ORDER BY expires_at
    LIMIT 1000
  )
)
INSERT INTO auth_rate_limits (
  scope,
  subject_hash,
  attempts,
  window_started_at,
  expires_at
)
VALUES ($1, $2, 1, now(), $3)
ON CONFLICT (scope, subject_hash) DO UPDATE
SET attempts = CASE
      WHEN auth_rate_limits.expires_at <= now() THEN 1
      ELSE auth_rate_limits.attempts + 1
    END,
    window_started_at = CASE
      WHEN auth_rate_limits.expires_at <= now() THEN now()
      ELSE auth_rate_limits.window_started_at
    END,
    expires_at = CASE
      WHEN auth_rate_limits.expires_at <= now() THEN EXCLUDED.expires_at
      ELSE auth_rate_limits.expires_at
    END
RETURNING attempts, expires_at
`

type IncrementAuthRateLimitParams struct {
	Scope       string             `json:"scope"`
	SubjectHash []byte             `json:"subject_hash"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
}

type IncrementAuthRateLimitRow struct {
	Attempts  int32              `json:"attempts"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) IncrementAuthRateLimit(ctx context.Context, arg IncrementAuthRateLimitParams) (IncrementAuthRateLimitRow, error) {
	row := q.db.QueryRow(ctx, incrementAuthRateLimit, arg.Scope, arg.SubjectHash, arg.ExpiresAt)
	var i IncrementAuthRateLimitRow
	err := row.Scan(&i.Attempts, &i.ExpiresAt)
	return i, err
}

const storeAuthEphemeralState = `-- name: StoreAuthEphemeralState :exec
WITH expired AS (
  DELETE FROM auth_ephemeral_states
  WHERE (purpose, key_hash) IN (
    SELECT purpose, key_hash
    FROM auth_ephemeral_states
    WHERE expires_at <= now()
    ORDER BY expires_at
    LIMIT 1000
  )
)
INSERT INTO auth_ephemeral_states (purpose, key_hash, payload, expires_at)
VALUES ($1, $2, $3, $4)
ON CONFLICT (purpose, key_hash) DO UPDATE
SET payload = EXCLUDED.payload,
    expires_at = EXCLUDED.expires_at,
    created_at = now()
`

type StoreAuthEphemeralStateParams struct {
	Purpose   string             `json:"purpose"`
	KeyHash   []byte             `json:"key_hash"`
	Payload   []byte             `json:"payload"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) StoreAuthEphemeralState(ctx context.Context, arg StoreAuthEphemeralStateParams) error {
	_, err := q.db.Exec(ctx, storeAuthEphemeralState,
		arg.Purpose,
		arg.KeyHash,
		arg.Payload,
		arg.ExpiresAt,
	)
	return err
}
