// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: captures.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const backfillLinkFetchQueue = `-- name: BackfillLinkFetchQueue :execrows
UPDATE captures
SET transcription_status = 'pending',
    transcription_attempts = 0,
    next_transcription_at = now()
WHERE media_key IS NULL
  AND deleted_at IS NULL
  -- Bulk content imports intentionally skip automatic external fan-out. A
  -- later user edit still goes through reconcileLinkFetch and may enqueue the
  -- single Capture normally.
  AND source <> 'markdown_import'
  AND transcript IS NULL
  AND transcription_status = 'none'
  AND raw_text ~* 'https?://'
`

// One-time enqueue of pre-existing text captures that carry a URL but were never
// link-enriched. Run once when the link-fetch worker starts, so history is only
// touched when the feature is actually enabled. The coarse `~*` presence check
// just gates entry to the queue; the worker derives the exact URL from the text
// (capture.FirstURL) — the URL grammar stays defined once, in Go.
func (q *Queries) BackfillLinkFetchQueue(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, backfillLinkFetchQueue)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const claimPendingLinkFetch = `-- name: ClaimPendingLinkFetch :one
UPDATE captures
SET transcription_status = 'processing',
    transcription_attempts = transcription_attempts + 1,
    next_transcription_at = now() + interval '10 minutes'
WHERE id = (
  SELECT id
  FROM captures
  WHERE transcription_status IN ('pending', 'processing', 'failed')
    AND transcription_attempts < 2147483647
    AND media_key IS NULL
    AND deleted_at IS NULL
    AND next_transcription_at <= now()
  ORDER BY next_transcription_at, created_at
  FOR UPDATE SKIP LOCKED
  LIMIT 1
)
RETURNING id, user_id, raw_text, media_url, media_type, classified_as, task_id, created_at, source, transcript, transcription_status, transcription_model, transcription_attempts, transcribed_at, next_transcription_at, audio_duration_sec, media_key, remind_at, deleted_at, remind_hide, todo_at, done_at, link_url
`

// Link enrichment only (media_key IS NULL). Symmetric to
// ClaimPendingTranscription; the media_key split keeps the two workers from
// claiming each other's rows out of the shared status column.
func (q *Queries) ClaimPendingLinkFetch(ctx context.Context) (Capture, error) {
	row := q.db.QueryRow(ctx, claimPendingLinkFetch)
	var i Capture
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RawText,
		&i.MediaUrl,
		&i.MediaType,
		&i.ClassifiedAs,
		&i.TaskID,
		&i.CreatedAt,
		&i.Source,
		&i.Transcript,
		&i.TranscriptionStatus,
		&i.TranscriptionModel,
		&i.TranscriptionAttempts,
		&i.TranscribedAt,
		&i.NextTranscriptionAt,
		&i.AudioDurationSec,
		&i.MediaKey,
		&i.RemindAt,
		&i.DeletedAt,
		&i.RemindHide,
		&i.TodoAt,
		&i.DoneAt,
		&i.LinkUrl,
	)
	return i, err
}

const claimPendingTranscription = `-- name: ClaimPendingTranscription :one
UPDATE captures
SET transcription_status = 'processing',
    transcription_attempts = transcription_attempts + 1,
    next_transcription_at = now() + interval '10 minutes'
WHERE id = (
  SELECT id
  FROM captures
  WHERE transcription_status IN ('pending', 'processing')
    AND transcription_attempts < 2147483647
    AND media_key IS NOT NULL
    AND deleted_at IS NULL
    AND next_transcription_at <= now()
  ORDER BY next_transcription_at, created_at
  FOR UPDATE SKIP LOCKED
  LIMIT 1
)
RETURNING id, user_id, raw_text, media_url, media_type, classified_as, task_id, created_at, source, transcript, transcription_status, transcription_model, transcription_attempts, transcribed_at, next_transcription_at, audio_duration_sec, media_key, remind_at, deleted_at, remind_hide, todo_at, done_at, link_url
`

// Media transcription only (media_key IS NOT NULL). Text captures with a URL
// share this status column for link enrichment; ClaimPendingLinkFetch claims
// those. The media_key split keeps the two workers off each other's rows.
func (q *Queries) ClaimPendingTranscription(ctx context.Context) (Capture, error) {
	row := q.db.QueryRow(ctx, claimPendingTranscription)
	var i Capture
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RawText,
		&i.MediaUrl,
		&i.MediaType,
		&i.ClassifiedAs,
		&i.TaskID,
		&i.CreatedAt,
		&i.Source,
		&i.Transcript,
		&i.TranscriptionStatus,
		&i.TranscriptionModel,
		&i.TranscriptionAttempts,
		&i.TranscribedAt,
		&i.NextTranscriptionAt,
		&i.AudioDurationSec,
		&i.MediaKey,
		&i.RemindAt,
		&i.DeletedAt,
		&i.RemindHide,
		&i.TodoAt,
		&i.DoneAt,
		&i.LinkUrl,
	)
	return i, err
}

const clearCaptureLinkFetch = `-- name: ClearCaptureLinkFetch :exec
UPDATE captures
SET link_url = NULL,
    transcript = NULL,
    transcription_status = 'none',
    transcription_model = NULL,
    transcribed_at = NULL,
    transcription_attempts = 0,
    next_transcription_at = NULL
WHERE id = $1 AND media_key IS NULL AND deleted_at IS NULL
`

// The URL was edited out of a text capture: drop the link-derived transcript and
// its scheduling so search matches the text again (text is the source of truth,
// like the #todo tag). Guarded to text captures (media_key IS NULL), whose
// transcript can only be link-derived — a media capture's transcript is
// Whisper/OCR output and must never be cleared here.
func (q *Queries) ClearCaptureLinkFetch(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearCaptureLinkFetch, id)
	return err
}

const completeCaptureLinkFetch = `-- name: CompleteCaptureLinkFetch :execrows
UPDATE captures
SET transcript = $2,
    link_url = $3,
    transcription_status = 'completed',
    transcription_model = $4,
    transcribed_at = now(),
    next_transcription_at = NULL
WHERE id = $1
  AND media_key IS NULL
  AND deleted_at IS NULL
  AND link_url = $3
  AND transcription_status = 'processing'
`

type CompleteCaptureLinkFetchParams struct {
	ID                 uuid.UUID   `json:"id"`
	Transcript         pgtype.Text `json:"transcript"`
	LinkUrl            pgtype.Text `json:"link_url"`
	TranscriptionModel pgtype.Text `json:"transcription_model"`
}

// Store the fetched page text as the capture's transcript (now its indexable
// content) and record the resolved URL, so a backfilled row that entered the
// queue without link_url ends up with the URL the worker actually fetched.
// The URL + processing predicate is a compare-and-set lease: an older request
// that finishes after the user changed/removed the URL must not restore stale
// content or cancel the replacement job.
func (q *Queries) CompleteCaptureLinkFetch(ctx context.Context, arg CompleteCaptureLinkFetchParams) (int64, error) {
	result, err := q.db.Exec(ctx, completeCaptureLinkFetch,
		arg.ID,
		arg.Transcript,
		arg.LinkUrl,
		arg.TranscriptionModel,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const completeCaptureTranscription = `-- name: CompleteCaptureTranscription :execrows
UPDATE captures
SET transcript = $2,
    transcription_status = 'completed',
    transcription_model = $3,
    transcribed_at = now(),
    next_transcription_at = NULL
WHERE id = $1
  AND media_key IS NOT NULL
  AND deleted_at IS NULL
  AND transcription_status = 'processing'
  AND next_transcription_at = $4
`

type CompleteCaptureTranscriptionParams struct {
	ID                 uuid.UUID          `json:"id"`
	Transcript         pgtype.Text        `json:"transcript"`
	TranscriptionModel pgtype.Text        `json:"transcription_model"`
	LeaseExpiresAt     pgtype.Timestamptz `json:"lease_expires_at"`
}

// next_transcription_at is the claim's lease token. Requiring the exact token
// prevents a worker whose lease expired from overwriting a newer claimant.
func (q *Queries) CompleteCaptureTranscription(ctx context.Context, arg CompleteCaptureTranscriptionParams) (int64, error) {
	result, err := q.db.Exec(ctx, completeCaptureTranscription,
		arg.ID,
		arg.Transcript,
		arg.TranscriptionModel,
		arg.LeaseExpiresAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createCapture = `-- name: CreateCapture :one
INSERT INTO captures (user_id, raw_text, media_url, media_type, source, todo_at, done_at)
VALUES ($1, $2, $3, $4, $5, $6::timestamptz, $7::timestamptz)
RETURNING id, user_id, raw_text, media_url, media_type, classified_as, task_id, created_at, source, transcript, transcription_status, transcription_model, transcription_attempts, transcribed_at, next_transcription_at, audio_duration_sec, media_key, remind_at, deleted_at, remind_hide, todo_at, done_at, link_url
`

type CreateCaptureParams struct {
	UserID    uuid.UUID          `json:"user_id"`
	RawText   pgtype.Text        `json:"raw_text"`
	MediaUrl  pgtype.Text        `json:"media_url"`
	MediaType CaptureMediaType   `json:"media_type"`
	Source    string             `json:"source"`
	TodoAt    pgtype.Timestamptz `json:"todo_at"`
	DoneAt    pgtype.Timestamptz `json:"done_at"`
}

// todo_at/done_at are derived from the raw text by the handler (the #todo tag
// is the todo facet's only entry point; see internal/capture/todotag.go).
func (q *Queries) CreateCapture(ctx context.Context, arg CreateCaptureParams) (Capture, error) {
	row := q.db.QueryRow(ctx, createCapture,
		arg.UserID,
		arg.RawText,
		arg.MediaUrl,
		arg.MediaType,
		arg.Source,
		arg.TodoAt,
		arg.DoneAt,
	)
	var i Capture
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RawText,
		&i.MediaUrl,
		&i.MediaType,
		&i.ClassifiedAs,
		&i.TaskID,
		&i.CreatedAt,
		&i.Source,
		&i.Transcript,
		&i.TranscriptionStatus,
		&i.TranscriptionModel,
		&i.TranscriptionAttempts,
		&i.TranscribedAt,
		&i.NextTranscriptionAt,
		&i.AudioDurationSec,
		&i.MediaKey,
		&i.RemindAt,
		&i.DeletedAt,
		&i.RemindHide,
		&i.TodoAt,
		&i.DoneAt,
		&i.LinkUrl,
	)
	return i, err
}

const createCaptureWithID = `-- name: CreateCaptureWithID :one
INSERT INTO captures (id, user_id, raw_text, media_type, source, todo_at, done_at)
VALUES (
  $1::uuid,
  $2::uuid,
  $3::text,
  'text',
  $4::text,
  $5::timestamptz,
  $6::timestamptz
)
ON CONFLICT (id) DO NOTHING
RETURNING id, user_id, raw_text, media_url, media_type, classified_as, task_id, created_at, source, transcript, transcription_status, transcription_model, transcription_attempts, transcribed_at, next_transcription_at, audio_duration_sec, media_key, remind_at, deleted_at, remind_hide, todo_at, done_at, link_url
`

type CreateCaptureWithIDParams struct {
	ID      uuid.UUID          `json:"id"`
	UserID  uuid.UUID          `json:"user_id"`
	RawText string             `json:"raw_text"`
	Source  string             `json:"source"`
	TodoAt  pgtype.Timestamptz `json:"todo_at"`
	DoneAt  pgtype.Timestamptz `json:"done_at"`
}

// A client-generated UUID is the stable operation identity for multi-service
// attachment creation. Retrying the same operation returns the original row
// instead of creating a duplicate Capture.
func (q *Queries) CreateCaptureWithID(ctx context.Context, arg CreateCaptureWithIDParams) (Capture, error) {
	row := q.db.QueryRow(ctx, createCaptureWithID,
		arg.ID,
		arg.UserID,
		arg.RawText,
		arg.Source,
		arg.TodoAt,
		arg.DoneAt,
	)
	var i Capture
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RawText,
		&i.MediaUrl,
		&i.MediaType,
		&i.ClassifiedAs,
		&i.TaskID,
		&i.CreatedAt,
		&i.Source,
		&i.Transcript,
		&i.TranscriptionStatus,
		&i.TranscriptionModel,
		&i.TranscriptionAttempts,
		&i.TranscribedAt,
		&i.NextTranscriptionAt,
		&i.AudioDurationSec,
		&i.MediaKey,
		&i.RemindAt,
		&i.DeletedAt,
		&i.RemindHide,
		&i.TodoAt,
		&i.DoneAt,
		&i.LinkUrl,
	)
	return i, err
}

const createUploadedCapture = `-- name: CreateUploadedCapture :one
INSERT INTO captures (
  id,
  user_id,
  media_url,
  media_type,
  source,
  media_key,
  audio_duration_sec,
  raw_text,
  todo_at,
  done_at,
  remind_at,
  remind_hide,
  transcription_status,
  next_transcription_at
)
VALUES (
  $1::uuid,
  $2::uuid,
  $3::text,
  $4::capture_media_type,
  $5::text,
  $6::text,
  $7::integer,
  $8::text,
  $9::timestamptz,
  $10::timestamptz,
  $11::timestamptz,
  $12::boolean,
  CASE
    WHEN $4::capture_media_type = 'audio'
      AND $7::integer IS NOT NULL
      AND $7::integer <= 300
      AND $13::boolean
    THEN 'pending'::transcription_status
    WHEN $4::capture_media_type = 'audio'
    THEN 'skipped'::transcription_status
    WHEN $4::capture_media_type = 'image'
      AND $14::boolean
    THEN 'pending'::transcription_status
    WHEN $4::capture_media_type = 'image'
    THEN 'skipped'::transcription_status
    ELSE 'none'::transcription_status
  END,
  CASE
    WHEN $4::capture_media_type = 'audio'
      AND $7::integer IS NOT NULL
      AND $7::integer <= 300
      AND $13::boolean
    THEN now()
    WHEN $4::capture_media_type = 'image'
      AND $14::boolean
    THEN now()
    ELSE NULL
  END
)
ON CONFLICT (id) DO NOTHING
RETURNING id, user_id, raw_text, media_url, media_type, classified_as, task_id, created_at, source, transcript, transcription_status, transcription_model, transcription_attempts, transcribed_at, next_transcription_at, audio_duration_sec, media_key, remind_at, deleted_at, remind_hide, todo_at, done_at, link_url
`

type CreateUploadedCaptureParams struct {
	ID                   uuid.UUID          `json:"id"`
	UserID               uuid.UUID          `json:"user_id"`
	MediaUrl             string             `json:"media_url"`
	MediaType            CaptureMediaType   `json:"media_type"`
	Source               string             `json:"source"`
	MediaKey             string             `json:"media_key"`
	AudioDurationSec     pgtype.Int4        `json:"audio_duration_sec"`
	RawText              pgtype.Text        `json:"raw_text"`
	TodoAt               pgtype.Timestamptz `json:"todo_at"`
	DoneAt               pgtype.Timestamptz `json:"done_at"`
	RemindAt             pgtype.Timestamptz `json:"remind_at"`
	RemindHide           bool               `json:"remind_hide"`
	TranscriptionEnabled bool               `json:"transcription_enabled"`
	VisionEnabled        bool               `json:"vision_enabled"`
}

// raw_text is the composer draft sent along with the upload; like
// CreateCapture, todo_at/done_at are derived from it by the handler (the
// #todo tag is the todo facet's only entry point; see
// internal/capture/todotag.go).
func (q *Queries) CreateUploadedCapture(ctx context.Context, arg CreateUploadedCaptureParams) (Capture, error) {
	row := q.db.QueryRow(ctx, createUploadedCapture,
		arg.ID,
		arg.UserID,
		arg.MediaUrl,
		arg.MediaType,
		arg.Source,
		arg.MediaKey,
		arg.AudioDurationSec,
		arg.RawText,
		arg.TodoAt,
		arg.DoneAt,
		arg.RemindAt,
		arg.RemindHide,
		arg.TranscriptionEnabled,
		arg.VisionEnabled,
	)
	var i Capture
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RawText,
		&i.MediaUrl,
		&i.MediaType,
		&i.ClassifiedAs,
		&i.TaskID,
		&i.CreatedAt,
		&i.Source,
		&i.Transcript,
		&i.TranscriptionStatus,
		&i.TranscriptionModel,
		&i.TranscriptionAttempts,
		&i.TranscribedAt,
		&i.NextTranscriptionAt,
		&i.AudioDurationSec,
		&i.MediaKey,
		&i.RemindAt,
		&i.DeletedAt,
		&i.RemindHide,
		&i.TodoAt,
		&i.DoneAt,
		&i.LinkUrl,
	)
	return i, err
}

const deleteCapture = `-- name: DeleteCapture :one
WITH deleted AS (
  UPDATE captures
  SET deleted_at = now()
  WHERE captures.id = $1
    AND captures.user_id = $2
    AND captures.deleted_at IS NULL
  RETURNING captures.id
), revoked AS (
  UPDATE capture_shares
  SET revoked_at = now()
  WHERE capture_id IN (SELECT id FROM deleted)
    AND user_id = $2
    AND revoked_at IS NULL
)
SELECT deleted.id FROM deleted
`

type DeleteCaptureParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

// Soft delete (project convention: never hard-DELETE user data). Revoke every
// active public snapshot in the same statement, so restoring the Capture can
// never make an old link public again. A second delete matches no row and
// returns pgx.ErrNoRows, which the handler maps to 404.
func (q *Queries) DeleteCapture(ctx context.Context, arg DeleteCaptureParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, deleteCapture, arg.ID, arg.UserID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const dueReminders = `-- name: DueReminders :many
SELECT id, user_id, raw_text, media_url, media_type, classified_as, task_id, created_at, source, transcript, transcription_status, transcription_model, transcription_attempts, transcribed_at, next_transcription_at, audio_duration_sec, media_key, remind_at, deleted_at, remind_hide, todo_at, done_at, link_url FROM captures
WHERE user_id = $1
  AND deleted_at IS NULL
  AND remind_at IS NOT NULL
  AND remind_at > $2::timestamptz
  AND remind_at <= $3::timestamptz
  AND (
    NOT $4::boolean
    OR (remind_at, id) < (
      $5::timestamptz,
      $6::uuid
    )
  )
ORDER BY remind_at DESC, id DESC
LIMIT $7
`

type DueRemindersParams struct {
	UserID    uuid.UUID          `json:"user_id"`
	Since     pgtype.Timestamptz `json:"since"`
	Until     pgtype.Timestamptz `json:"until"`
	HasBefore bool               `json:"has_before"`
	BeforeAt  pgtype.Timestamptz `json:"before_at"`
	BeforeID  uuid.UUID          `json:"before_id"`
	PageSize  int32              `json:"page_size"`
}

// A bounded page of reminders that came due in (since, until]. Callers walk
// backwards with (before_at, before_id), which keeps equal timestamps stable and
// lets the desktop advance its durable checkpoint only after every page succeeds.
func (q *Queries) DueReminders(ctx context.Context, arg DueRemindersParams) ([]Capture, error) {
	rows, err := q.db.Query(ctx, dueReminders,
		arg.UserID,
		arg.Since,
		arg.Until,
		arg.HasBefore,
		arg.BeforeAt,
		arg.BeforeID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Capture
	for rows.Next() {
		var i Capture
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.RawText,
			&i.MediaUrl,
			&i.MediaType,
			&i.ClassifiedAs,
			&i.TaskID,
			&i.CreatedAt,
			&i.Source,
			&i.Transcript,
			&i.TranscriptionStatus,
			&i.TranscriptionModel,
			&i.TranscriptionAttempts,
			&i.TranscribedAt,
			&i.NextTranscriptionAt,
			&i.AudioDurationSec,
			&i.MediaKey,
			&i.RemindAt,
			&i.DeletedAt,
			&i.RemindHide,
			&i.TodoAt,
			&i.DoneAt,
			&i.LinkUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const emptyTrash = `-- name: EmptyTrash :many
WITH target AS (
    SELECT id, media_key
    FROM captures
    WHERE captures.user_id = $1
      AND deleted_at IS NOT NULL
    FOR UPDATE
),
queued AS (
    INSERT INTO capture_media_deletions (object_key)
    SELECT media_key
    FROM target
    WHERE media_key IS NOT NULL AND media_key <> ''
    ON CONFLICT (object_key) DO NOTHING
),
deleted AS (
    DELETE FROM captures
    USING target
    WHERE captures.id = target.id
    RETURNING captures.id
)
SELECT id FROM deleted
`

// Hard delete every trashed capture for the user (explicit "empty trash").
// Same cascade + transactional deletion-outbox semantics as
// PermanentDeleteCapture. Returns one id per deleted capture so the handler can
// report the exact purged count, including text captures with no media object.
func (q *Queries) EmptyTrash(ctx context.Context, userID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, emptyTrash, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const enqueueCaptureLinkFetch = `-- name: EnqueueCaptureLinkFetch :exec
UPDATE captures
SET link_url = $2,
    transcript = NULL,
    transcription_status = 'pending',
    transcription_model = NULL,
    transcribed_at = NULL,
    transcription_attempts = 0,
    next_transcription_at = now()
WHERE id = $1 AND media_key IS NULL AND deleted_at IS NULL
`

type EnqueueCaptureLinkFetchParams struct {
	ID      uuid.UUID   `json:"id"`
	LinkUrl pgtype.Text `json:"link_url"`
}

// Record the URL detected in a text capture and hand it to the link-fetch worker
// via the shared transcription_status machine. media_key IS NULL guards it to
// text captures (a media capture's queue slot belongs to transcription). Clear
// any old link-derived transcript immediately so search never keeps matching a
// stale page while the new URL is pending or has failed.
func (q *Queries) EnqueueCaptureLinkFetch(ctx context.Context, arg EnqueueCaptureLinkFetchParams) error {
	_, err := q.db.Exec(ctx, enqueueCaptureLinkFetch, arg.ID, arg.LinkUrl)
	return err
}

const failCaptureLinkFetch = `-- name: FailCaptureLinkFetch :execrows
UPDATE captures
SET transcription_status = CASE
      WHEN transcription_attempts >= 4 THEN 'failed'::transcription_status
      ELSE 'pending'::transcription_status
    END,
    next_transcription_at = CASE
      WHEN transcription_attempts >= 8 THEN NULL
      ELSE CASE transcription_attempts
      WHEN 1 THEN now() + interval '1 minute'
      WHEN 2 THEN now() + interval '5 minutes'
      WHEN 3 THEN now() + interval '30 minutes'
      ELSE now() + interval '24 hours'
      END
    END
WHERE id = $1
  AND media_key IS NULL
  AND deleted_at IS NULL
  AND link_url = $2::text
  AND transcription_status = 'processing'
`

type FailCaptureLinkFetchParams struct {
	ID      uuid.UUID `json:"id"`
	LinkUrl string    `json:"link_url"`
}

// Link-job counterpart to FailCaptureTranscription, guarded by the URL lease so
// an old failed request cannot strand a newly-enqueued URL. After the short
// retry budget is exhausted, keep a bounded daily self-heal schedule: a
// temporary provider outage gets several later chances, while a permanently
// hostile URL eventually leaves the shared single-worker queue.
func (q *Queries) FailCaptureLinkFetch(ctx context.Context, arg FailCaptureLinkFetchParams) (int64, error) {
	result, err := q.db.Exec(ctx, failCaptureLinkFetch, arg.ID, arg.LinkUrl)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const failCaptureTranscription = `-- name: FailCaptureTranscription :execrows
UPDATE captures
SET transcription_status = CASE
      WHEN transcription_attempts >= 4 THEN 'failed'::transcription_status
      ELSE 'pending'::transcription_status
    END,
    next_transcription_at = CASE transcription_attempts
      WHEN 1 THEN now() + interval '1 minute'
      WHEN 2 THEN now() + interval '5 minutes'
      WHEN 3 THEN now() + interval '30 minutes'
      ELSE NULL
    END
WHERE id = $1
  AND media_key IS NOT NULL
  AND deleted_at IS NULL
  AND transcription_status = 'processing'
  AND next_transcription_at = $2
`

type FailCaptureTranscriptionParams struct {
	ID             uuid.UUID          `json:"id"`
	LeaseExpiresAt pgtype.Timestamptz `json:"lease_expires_at"`
}

func (q *Queries) FailCaptureTranscription(ctx context.Context, arg FailCaptureTranscriptionParams) (int64, error) {
	result, err := q.db.Exec(ctx, failCaptureTranscription, arg.ID, arg.LeaseExpiresAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCapture = `-- name: GetCapture :one
SELECT id, user_id, raw_text, media_url, media_type, classified_as, task_id, created_at, source, transcript, transcription_status, transcription_model, transcription_attempts, transcribed_at, next_transcription_at, audio_duration_sec, media_key, remind_at, deleted_at, remind_hide, todo_at, done_at, link_url FROM captures
WHERE id = $1 AND user_id = $2 AND deleted_at IS NULL
`

type GetCaptureParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetCapture(ctx context.Context, arg GetCaptureParams) (Capture, error) {
	row := q.db.QueryRow(ctx, getCapture, arg.ID, arg.UserID)
	var i Capture
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RawText,
		&i.MediaUrl,
		&i.MediaType,
		&i.ClassifiedAs,
		&i.TaskID,
		&i.CreatedAt,
		&i.Source,
		&i.Transcript,
		&i.TranscriptionStatus,
		&i.TranscriptionModel,
		&i.TranscriptionAttempts,
		&i.TranscribedAt,
		&i.NextTranscriptionAt,
		&i.AudioDurationSec,
		&i.MediaKey,
		&i.RemindAt,
		&i.DeletedAt,
		&i.RemindHide,
		&i.TodoAt,
		&i.DoneAt,
		&i.LinkUrl,
	)
	return i, err
}

const getCaptureAnyState = `-- name: GetCaptureAnyState :one
SELECT id, user_id, raw_text, media_url, media_type, classified_as, task_id, created_at, source, transcript, transcription_status, transcription_model, transcription_attempts, transcribed_at, next_transcription_at, audio_duration_sec, media_key, remind_at, deleted_at, remind_hide, todo_at, done_at, link_url FROM captures
WHERE id = $1 AND user_id = $2
`

type GetCaptureAnyStateParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

// Idempotent remote-create paths must reserve an operation UUID even after the
// resulting capture is moved to Trash, otherwise a retry could overwrite its
// media object and attempt to recreate the same id.
func (q *Queries) GetCaptureAnyState(ctx context.Context, arg GetCaptureAnyStateParams) (Capture, error) {
	row := q.db.QueryRow(ctx, getCaptureAnyState, arg.ID, arg.UserID)
	var i Capture
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RawText,
		&i.MediaUrl,
		&i.MediaType,
		&i.ClassifiedAs,
		&i.TaskID,
		&i.CreatedAt,
		&i.Source,
		&i.Transcript,
		&i.TranscriptionStatus,
		&i.TranscriptionModel,
		&i.TranscriptionAttempts,
		&i.TranscribedAt,
		&i.NextTranscriptionAt,
		&i.AudioDurationSec,
		&i.MediaKey,
		&i.RemindAt,
		&i.DeletedAt,
		&i.RemindHide,
		&i.TodoAt,
		&i.DoneAt,
		&i.LinkUrl,
	)
	return i, err
}

const listCaptureContextAfter = `-- name: ListCaptureContextAfter :many
SELECT id, user_id, raw_text, media_url, media_type, classified_as, task_id, created_at, source, transcript, transcription_status, transcription_model, transcription_attempts, transcribed_at, next_transcription_at, audio_duration_sec, media_key, remind_at, deleted_at, remind_hide, todo_at, done_at, link_url FROM captures
WHERE user_id = $1
  AND deleted_at IS NULL
  AND (created_at, id) > (
    $2::timestamptz,
    $3::uuid
  )
ORDER BY created_at ASC, id ASC
LIMIT $4
`

type ListCaptureContextAfterParams struct {
	UserID          uuid.UUID          `json:"user_id"`
	AnchorCreatedAt pgtype.Timestamptz `json:"anchor_created_at"`
	AnchorID        uuid.UUID          `json:"anchor_id"`
	WindowSize      int32              `json:"window_size"`
}

func (q *Queries) ListCaptureContextAfter(ctx context.Context, arg ListCaptureContextAfterParams) ([]Capture, error) {
	rows, err := q.db.Query(ctx, listCaptureContextAfter,
		arg.UserID,
		arg.AnchorCreatedAt,
		arg.AnchorID,
		arg.WindowSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Capture
	for rows.Next() {
		var i Capture
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.RawText,
			&i.MediaUrl,
			&i.MediaType,
			&i.ClassifiedAs,
			&i.TaskID,
			&i.CreatedAt,
			&i.Source,
			&i.Transcript,
			&i.TranscriptionStatus,
			&i.TranscriptionModel,
			&i.TranscriptionAttempts,
			&i.TranscribedAt,
			&i.NextTranscriptionAt,
			&i.AudioDurationSec,
			&i.MediaKey,
			&i.RemindAt,
			&i.DeletedAt,
			&i.RemindHide,
			&i.TodoAt,
			&i.DoneAt,
			&i.LinkUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCaptureContextBefore = `-- name: ListCaptureContextBefore :many
SELECT id, user_id, raw_text, media_url, media_type, classified_as, task_id, created_at, source, transcript, transcription_status, transcription_model, transcription_attempts, transcribed_at, next_transcription_at, audio_duration_sec, media_key, remind_at, deleted_at, remind_hide, todo_at, done_at, link_url FROM captures
WHERE user_id = $1
  AND deleted_at IS NULL
  AND (created_at, id) < (
    $2::timestamptz,
    $3::uuid
  )
ORDER BY created_at DESC, id DESC
LIMIT $4
`

type ListCaptureContextBeforeParams struct {
	UserID          uuid.UUID          `json:"user_id"`
	AnchorCreatedAt pgtype.Timestamptz `json:"anchor_created_at"`
	AnchorID        uuid.UUID          `json:"anchor_id"`
	WindowSize      int32              `json:"window_size"`
}

func (q *Queries) ListCaptureContextBefore(ctx context.Context, arg ListCaptureContextBeforeParams) ([]Capture, error) {
	rows, err := q.db.Query(ctx, listCaptureContextBefore,
		arg.UserID,
		arg.AnchorCreatedAt,
		arg.AnchorID,
		arg.WindowSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Capture
	for rows.Next() {
		var i Capture
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.RawText,
			&i.MediaUrl,
			&i.MediaType,
			&i.ClassifiedAs,
			&i.TaskID,
			&i.CreatedAt,
			&i.Source,
			&i.Transcript,
			&i.TranscriptionStatus,
			&i.TranscriptionModel,
			&i.TranscriptionAttempts,
			&i.TranscribedAt,
			&i.NextTranscriptionAt,
			&i.AudioDurationSec,
			&i.MediaKey,
			&i.RemindAt,
			&i.DeletedAt,
			&i.RemindHide,
			&i.TodoAt,
			&i.DoneAt,
			&i.LinkUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCapturePage = `-- name: ListCapturePage :many
SELECT id, user_id, raw_text, media_url, media_type, classified_as, task_id, created_at, source, transcript, transcription_status, transcription_model, transcription_attempts, transcribed_at, next_transcription_at, audio_duration_sec, media_key, remind_at, deleted_at, remind_hide, todo_at, done_at, link_url FROM captures
WHERE user_id = $1
  AND deleted_at IS NULL
  AND (
    $2::text IS NULL
    OR ($2::text = 'open' AND todo_at IS NOT NULL AND done_at IS NULL)
    OR ($2::text = 'done' AND done_at IS NOT NULL)
  )
  AND (
    $3::timestamptz IS NULL
    OR (created_at, id) < (
      $3::timestamptz,
      $4::uuid
    )
  )
  AND (
    $5::boolean
    OR remind_at IS NULL
    OR remind_at <= now()
    OR NOT remind_hide
  )
ORDER BY created_at DESC, id DESC
LIMIT $6
`

type ListCapturePageParams struct {
	UserID          uuid.UUID          `json:"user_id"`
	Todo            pgtype.Text        `json:"todo"`
	CursorCreatedAt pgtype.Timestamptz `json:"cursor_created_at"`
	CursorID        pgtype.UUID        `json:"cursor_id"`
	IncludeReminded bool               `json:"include_reminded"`
	PageSize        int32              `json:"page_size"`
}

func (q *Queries) ListCapturePage(ctx context.Context, arg ListCapturePageParams) ([]Capture, error) {
	rows, err := q.db.Query(ctx, listCapturePage,
		arg.UserID,
		arg.Todo,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.IncludeReminded,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Capture
	for rows.Next() {
		var i Capture
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.RawText,
			&i.MediaUrl,
			&i.MediaType,
			&i.ClassifiedAs,
			&i.TaskID,
			&i.CreatedAt,
			&i.Source,
			&i.Transcript,
			&i.TranscriptionStatus,
			&i.TranscriptionModel,
			&i.TranscriptionAttempts,
			&i.TranscribedAt,
			&i.NextTranscriptionAt,
			&i.AudioDurationSec,
			&i.MediaKey,
			&i.RemindAt,
			&i.DeletedAt,
			&i.RemindHide,
			&i.TodoAt,
			&i.DoneAt,
			&i.LinkUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCapturesInRange = `-- name: ListCapturesInRange :many
SELECT id, user_id, raw_text, media_url, media_type, classified_as, task_id, created_at, source, transcript, transcription_status, transcription_model, transcription_attempts, transcribed_at, next_transcription_at, audio_duration_sec, media_key, remind_at, deleted_at, remind_hide, todo_at, done_at, link_url FROM captures
WHERE user_id = $1
  AND deleted_at IS NULL
  AND created_at >= $2
  AND created_at < $3
ORDER BY created_at
`

type ListCapturesInRangeParams struct {
	UserID      uuid.UUID          `json:"user_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	CreatedAt_2 pgtype.Timestamptz `json:"created_at_2"`
}

func (q *Queries) ListCapturesInRange(ctx context.Context, arg ListCapturesInRangeParams) ([]Capture, error) {
	rows, err := q.db.Query(ctx, listCapturesInRange, arg.UserID, arg.CreatedAt, arg.CreatedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Capture
	for rows.Next() {
		var i Capture
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.RawText,
			&i.MediaUrl,
			&i.MediaType,
			&i.ClassifiedAs,
			&i.TaskID,
			&i.CreatedAt,
			&i.Source,
			&i.Transcript,
			&i.TranscriptionStatus,
			&i.TranscriptionModel,
			&i.TranscriptionAttempts,
			&i.TranscribedAt,
			&i.NextTranscriptionAt,
			&i.AudioDurationSec,
			&i.MediaKey,
			&i.RemindAt,
			&i.DeletedAt,
			&i.RemindHide,
			&i.TodoAt,
			&i.DoneAt,
			&i.LinkUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTrashedCaptures = `-- name: ListTrashedCaptures :many
SELECT id, user_id, raw_text, media_url, media_type, classified_as, task_id, created_at, source, transcript, transcription_status, transcription_model, transcription_attempts, transcribed_at, next_transcription_at, audio_duration_sec, media_key, remind_at, deleted_at, remind_hide, todo_at, done_at, link_url FROM captures
WHERE user_id = $1 AND deleted_at IS NOT NULL
ORDER BY deleted_at DESC, id DESC
LIMIT $2
`

type ListTrashedCapturesParams struct {
	UserID      uuid.UUID `json:"user_id"`
	ResultLimit int32     `json:"result_limit"`
}

// Soft-deleted captures, for the trash view. Most-recently-deleted first.
// Capped: a user who never empties the trash would otherwise grow this
// response without bound. Older trashed rows stay restorable one-by-one once
// the newer ones are purged, and empty-trash always clears everything.
func (q *Queries) ListTrashedCaptures(ctx context.Context, arg ListTrashedCapturesParams) ([]Capture, error) {
	rows, err := q.db.Query(ctx, listTrashedCaptures, arg.UserID, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Capture
	for rows.Next() {
		var i Capture
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.RawText,
			&i.MediaUrl,
			&i.MediaType,
			&i.ClassifiedAs,
			&i.TaskID,
			&i.CreatedAt,
			&i.Source,
			&i.Transcript,
			&i.TranscriptionStatus,
			&i.TranscriptionModel,
			&i.TranscriptionAttempts,
			&i.TranscribedAt,
			&i.NextTranscriptionAt,
			&i.AudioDurationSec,
			&i.MediaKey,
			&i.RemindAt,
			&i.DeletedAt,
			&i.RemindHide,
			&i.TodoAt,
			&i.DoneAt,
			&i.LinkUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const minScheduledLinkFetchIn = `-- name: MinScheduledLinkFetchIn :one
SELECT COALESCE(EXTRACT(EPOCH FROM MIN(next_transcription_at) - now()), 0)::float8 AS next_in_seconds
FROM captures
WHERE transcription_status IN ('pending', 'processing', 'failed')
  AND media_key IS NULL
  AND deleted_at IS NULL
  AND next_transcription_at > now()
`

// Seconds until the earliest not-yet-claimable link-fetch job comes due (failure
// backoff or a crashed 'processing' lease). Link-job counterpart to
// MinScheduledTranscriptionIn; see its comment for why the clock math is in SQL.
func (q *Queries) MinScheduledLinkFetchIn(ctx context.Context) (float64, error) {
	row := q.db.QueryRow(ctx, minScheduledLinkFetchIn)
	var next_in_seconds float64
	err := row.Scan(&next_in_seconds)
	return next_in_seconds, err
}

const minScheduledTranscriptionIn = `-- name: MinScheduledTranscriptionIn :one
SELECT COALESCE(EXTRACT(EPOCH FROM MIN(next_transcription_at) - now()), 0)::float8 AS next_in_seconds
FROM captures
WHERE transcription_status IN ('pending', 'processing')
  AND media_key IS NOT NULL
  AND deleted_at IS NULL
  AND next_transcription_at > now()
`

// Seconds until the earliest not-yet-claimable transcription work comes due: a
// failed attempt's backoff retry, or a 'processing' lease that would come free
// after a crash. The worker reads this after every drain so its wake-up timer
// never forgets a retry scheduled by an earlier drain. Zero when nothing is
// scheduled. The subtraction happens here because claimability is judged by
// the database clock — computing it against the Go clock skews the wait by
// whatever the two clocks disagree on.
func (q *Queries) MinScheduledTranscriptionIn(ctx context.Context) (float64, error) {
	row := q.db.QueryRow(ctx, minScheduledTranscriptionIn)
	var next_in_seconds float64
	err := row.Scan(&next_in_seconds)
	return next_in_seconds, err
}

const pendingReminders = `-- name: PendingReminders :many
SELECT id, user_id, raw_text, media_url, media_type, classified_as, task_id, created_at, source, transcript, transcription_status, transcription_model, transcription_attempts, transcribed_at, next_transcription_at, audio_duration_sec, media_key, remind_at, deleted_at, remind_hide, todo_at, done_at, link_url FROM captures
WHERE user_id = $1
  AND deleted_at IS NULL
  AND remind_at IS NOT NULL
  AND remind_at > now()
ORDER BY remind_at
`

// All not-yet-due reminders (remind_at > now), so the desktop app can reconcile
// its scheduled OS notifications on launch.
func (q *Queries) PendingReminders(ctx context.Context, userID uuid.UUID) ([]Capture, error) {
	rows, err := q.db.Query(ctx, pendingReminders, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Capture
	for rows.Next() {
		var i Capture
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.RawText,
			&i.MediaUrl,
			&i.MediaType,
			&i.ClassifiedAs,
			&i.TaskID,
			&i.CreatedAt,
			&i.Source,
			&i.Transcript,
			&i.TranscriptionStatus,
			&i.TranscriptionModel,
			&i.TranscriptionAttempts,
			&i.TranscribedAt,
			&i.NextTranscriptionAt,
			&i.AudioDurationSec,
			&i.MediaKey,
			&i.RemindAt,
			&i.DeletedAt,
			&i.RemindHide,
			&i.TodoAt,
			&i.DoneAt,
			&i.LinkUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const permanentDeleteCapture = `-- name: PermanentDeleteCapture :one
WITH target AS (
    SELECT id, media_key
    FROM captures
    WHERE captures.id = $1
      AND captures.user_id = $2
      AND deleted_at IS NOT NULL
    FOR UPDATE
),
queued AS (
    INSERT INTO capture_media_deletions (object_key)
    SELECT media_key
    FROM target
    WHERE media_key IS NOT NULL AND media_key <> ''
    ON CONFLICT (object_key) DO NOTHING
),
deleted AS (
    DELETE FROM captures
    USING target
    WHERE captures.id = target.id
    RETURNING captures.id
)
SELECT id FROM deleted
`

type PermanentDeleteCaptureParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

// Hard delete, allowed ONLY from the trash (deleted_at IS NOT NULL) as an
// explicit user action — the macOS "Recently Deleted" model: normal delete is
// soft, the trash offers permanent removal for content the user truly wants gone
// (a mistaken or sensitive capture). FK ON DELETE CASCADE clears the derived rows
// (capture_links, capture_attachments, capture_embeddings, capture_metadata).
// If media exists, enqueue its R2 key in the durable deletion outbox in the
// SAME statement as the hard delete. A request cancellation or provider outage
// can therefore never turn the object key into an untraceable orphan.
// No row (live capture or wrong owner) → pgx.ErrNoRows → 404.
func (q *Queries) PermanentDeleteCapture(ctx context.Context, arg PermanentDeleteCaptureParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, permanentDeleteCapture, arg.ID, arg.UserID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const prepareCaptureLinkFetch = `-- name: PrepareCaptureLinkFetch :execrows
UPDATE captures
SET link_url = $1::text
WHERE id = $2
  AND media_key IS NULL
  AND deleted_at IS NULL
  AND transcription_status = 'processing'
  AND (link_url IS NULL OR link_url = $1::text)
`

type PrepareCaptureLinkFetchParams struct {
	LinkUrl string    `json:"link_url"`
	ID      uuid.UUID `json:"id"`
}

// Pin the URL a claimed job is about to fetch. Backfilled jobs enter the queue
// with link_url NULL and derive the exact target from raw_text in Go; persisting
// it before the network request gives every terminal write a generation token.
// If an edit already superseded this claim (status is no longer processing or a
// different URL is stored), zero rows are updated and the stale worker stops.
func (q *Queries) PrepareCaptureLinkFetch(ctx context.Context, arg PrepareCaptureLinkFetchParams) (int64, error) {
	result, err := q.db.Exec(ctx, prepareCaptureLinkFetch, arg.LinkUrl, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const restoreCapture = `-- name: RestoreCapture :one
UPDATE captures
SET deleted_at = NULL
WHERE id = $1 AND user_id = $2 AND deleted_at IS NOT NULL
RETURNING id, user_id, raw_text, media_url, media_type, classified_as, task_id, created_at, source, transcript, transcription_status, transcription_model, transcription_attempts, transcribed_at, next_transcription_at, audio_duration_sec, media_key, remind_at, deleted_at, remind_hide, todo_at, done_at, link_url
`

type RestoreCaptureParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

// Undo a soft delete. Idempotent — restoring a live capture matches no row and
// returns pgx.ErrNoRows, which the handler maps to 404. The embedding/metadata
// side rows were never dropped on soft delete, so no reindex is needed.
func (q *Queries) RestoreCapture(ctx context.Context, arg RestoreCaptureParams) (Capture, error) {
	row := q.db.QueryRow(ctx, restoreCapture, arg.ID, arg.UserID)
	var i Capture
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RawText,
		&i.MediaUrl,
		&i.MediaType,
		&i.ClassifiedAs,
		&i.TaskID,
		&i.CreatedAt,
		&i.Source,
		&i.Transcript,
		&i.TranscriptionStatus,
		&i.TranscriptionModel,
		&i.TranscriptionAttempts,
		&i.TranscribedAt,
		&i.NextTranscriptionAt,
		&i.AudioDurationSec,
		&i.MediaKey,
		&i.RemindAt,
		&i.DeletedAt,
		&i.RemindHide,
		&i.TodoAt,
		&i.DoneAt,
		&i.LinkUrl,
	)
	return i, err
}

const retryCaptureTranscription = `-- name: RetryCaptureTranscription :one
UPDATE captures
SET transcription_status = 'pending',
    transcription_attempts = 0,
    next_transcription_at = now()
WHERE id = $1
  AND user_id = $2
  AND deleted_at IS NULL
  -- A manual retry must not invalidate a live worker's claim. Expired claims
  -- are reclaimed by ClaimPendingTranscription after their lease comes due.
  AND transcription_status <> 'processing'
  AND (
    -- audio: same size guard the create path applies before queueing
    (media_type = 'audio' AND audio_duration_sec IS NOT NULL AND audio_duration_sec <= 300)
    -- image OCR has no duration guard; the worker routes it to vision transcription
    OR media_type = 'image'
  )
RETURNING id, user_id, raw_text, media_url, media_type, classified_as, task_id, created_at, source, transcript, transcription_status, transcription_model, transcription_attempts, transcribed_at, next_transcription_at, audio_duration_sec, media_key, remind_at, deleted_at, remind_hide, todo_at, done_at, link_url
`

type RetryCaptureTranscriptionParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) RetryCaptureTranscription(ctx context.Context, arg RetryCaptureTranscriptionParams) (Capture, error) {
	row := q.db.QueryRow(ctx, retryCaptureTranscription, arg.ID, arg.UserID)
	var i Capture
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RawText,
		&i.MediaUrl,
		&i.MediaType,
		&i.ClassifiedAs,
		&i.TaskID,
		&i.CreatedAt,
		&i.Source,
		&i.Transcript,
		&i.TranscriptionStatus,
		&i.TranscriptionModel,
		&i.TranscriptionAttempts,
		&i.TranscribedAt,
		&i.NextTranscriptionAt,
		&i.AudioDurationSec,
		&i.MediaKey,
		&i.RemindAt,
		&i.DeletedAt,
		&i.RemindHide,
		&i.TodoAt,
		&i.DoneAt,
		&i.LinkUrl,
	)
	return i, err
}

const setCaptureRemind = `-- name: SetCaptureRemind :one
UPDATE captures
SET remind_at = $1::timestamptz,
    remind_hide = $2::boolean
WHERE id = $3 AND user_id = $4 AND deleted_at IS NULL
RETURNING id, user_id, raw_text, media_url, media_type, classified_as, task_id, created_at, source, transcript, transcription_status, transcription_model, transcription_attempts, transcribed_at, next_transcription_at, audio_duration_sec, media_key, remind_at, deleted_at, remind_hide, todo_at, done_at, link_url
`

type SetCaptureRemindParams struct {
	RemindAt   pgtype.Timestamptz `json:"remind_at"`
	RemindHide bool               `json:"remind_hide"`
	ID         uuid.UUID          `json:"id"`
	UserID     uuid.UUID          `json:"user_id"`
}

// Set or clear (remind_at = NULL) a capture's reminder. Independent of content
// edits so the semantics stay separate. Only the browse path filters on this;
// search/recall never do.
//
// remind_hide splits notify from hide: true (default) hides the capture from
// browse until due; false keeps it visible the whole time yet still notifies
// (notify-only). When the reminder is cleared (remind_at = NULL) the flag is
// moot — a null remind_at is always shown regardless of remind_hide.
func (q *Queries) SetCaptureRemind(ctx context.Context, arg SetCaptureRemindParams) (Capture, error) {
	row := q.db.QueryRow(ctx, setCaptureRemind,
		arg.RemindAt,
		arg.RemindHide,
		arg.ID,
		arg.UserID,
	)
	var i Capture
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RawText,
		&i.MediaUrl,
		&i.MediaType,
		&i.ClassifiedAs,
		&i.TaskID,
		&i.CreatedAt,
		&i.Source,
		&i.Transcript,
		&i.TranscriptionStatus,
		&i.TranscriptionModel,
		&i.TranscriptionAttempts,
		&i.TranscribedAt,
		&i.NextTranscriptionAt,
		&i.AudioDurationSec,
		&i.MediaKey,
		&i.RemindAt,
		&i.DeletedAt,
		&i.RemindHide,
		&i.TodoAt,
		&i.DoneAt,
		&i.LinkUrl,
	)
	return i, err
}

const skipCaptureLinkFetch = `-- name: SkipCaptureLinkFetch :execrows
UPDATE captures
SET transcription_status = 'skipped',
    next_transcription_at = NULL
WHERE id = $1
  AND media_key IS NULL
  AND deleted_at IS NULL
  AND link_url = $2::text
  AND transcription_status = 'processing'
`

type SkipCaptureLinkFetchParams struct {
	ID      uuid.UUID `json:"id"`
	LinkUrl string    `json:"link_url"`
}

// A successfully fetched page had no extractable text. Like complete/fail, only
// the still-current claimed URL may leave the queue.
func (q *Queries) SkipCaptureLinkFetch(ctx context.Context, arg SkipCaptureLinkFetchParams) (int64, error) {
	result, err := q.db.Exec(ctx, skipCaptureLinkFetch, arg.ID, arg.LinkUrl)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const skipCaptureTranscription = `-- name: SkipCaptureTranscription :execrows
UPDATE captures
SET transcription_status = 'skipped',
    next_transcription_at = NULL
WHERE id = $1
  AND media_key IS NOT NULL
  AND deleted_at IS NULL
  AND transcription_status = 'processing'
  AND next_transcription_at = $2
`

type SkipCaptureTranscriptionParams struct {
	ID             uuid.UUID          `json:"id"`
	LeaseExpiresAt pgtype.Timestamptz `json:"lease_expires_at"`
}

// Mark a capture's transcription skipped and clear its retry schedule, so it
// leaves the worker queue. Used to enforce the vision opt-out at the sink: an
// image that reached 'pending' (e.g. via retry) while VISION_ENABLED is off is
// skipped instead of being sent to the vision provider. The lease token keeps
// a stale worker from skipping a task that another worker has reclaimed.
func (q *Queries) SkipCaptureTranscription(ctx context.Context, arg SkipCaptureTranscriptionParams) (int64, error) {
	result, err := q.db.Exec(ctx, skipCaptureTranscription, arg.ID, arg.LeaseExpiresAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const skipUnresolvedLinkFetch = `-- name: SkipUnresolvedLinkFetch :execrows
UPDATE captures
SET transcription_status = 'skipped',
    next_transcription_at = NULL
WHERE id = $1
  AND media_key IS NULL
  AND deleted_at IS NULL
  AND link_url IS NULL
  AND transcription_status = 'processing'
`

// A coarse SQL backfill match contained no URL accepted by the Go grammar. Only
// skip the still-current NULL-link claim; if the user added a real URL after the
// claim, EnqueueCaptureLinkFetch has already replaced both link_url and status.
func (q *Queries) SkipUnresolvedLinkFetch(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, skipUnresolvedLinkFetch, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateCapture = `-- name: UpdateCapture :one
UPDATE captures
SET
  raw_text      = COALESCE($1::text,   raw_text),
  transcript    = COALESCE($2::text, transcript),
  todo_at = CASE
    WHEN $1::text IS NULL THEN todo_at
    WHEN NOT $3::boolean THEN NULL
    ELSE COALESCE(todo_at, now())
  END,
  done_at = CASE
    WHEN $1::text IS NULL THEN done_at
    WHEN NOT $4::boolean THEN NULL
    WHEN $5::timestamptz IS NOT NULL THEN $5::timestamptz
    ELSE COALESCE(done_at, now())
  END
WHERE id = $6 AND user_id = $7 AND deleted_at IS NULL
RETURNING id, user_id, raw_text, media_url, media_type, classified_as, task_id, created_at, source, transcript, transcription_status, transcription_model, transcription_attempts, transcribed_at, next_transcription_at, audio_duration_sec, media_key, remind_at, deleted_at, remind_hide, todo_at, done_at, link_url
`

type UpdateCaptureParams struct {
	RawText     pgtype.Text        `json:"raw_text"`
	Transcript  pgtype.Text        `json:"transcript"`
	TodoPresent bool               `json:"todo_present"`
	TodoDone    bool               `json:"todo_done"`
	DoneDate    pgtype.Timestamptz `json:"done_date"`
	ID          uuid.UUID          `json:"id"`
	UserID      uuid.UUID          `json:"user_id"`
}

// When raw_text changes, todo_at/done_at follow the text (the #todo tag is
// authoritative; the handler parses it into todo_present/todo_done/done_date).
// A transcript-only patch (raw_text IS NULL) leaves both stamps untouched.
// todo_at keeps its original value while the tag stays present (first-entry
// index); done_at takes the tag's explicit date when given, else keeps the
// existing stamp, else now(). The CHECK (done_at IS NULL OR todo_at IS NOT
// NULL) holds because the parser only reports done on a present tag.
func (q *Queries) UpdateCapture(ctx context.Context, arg UpdateCaptureParams) (Capture, error) {
	row := q.db.QueryRow(ctx, updateCapture,
		arg.RawText,
		arg.Transcript,
		arg.TodoPresent,
		arg.TodoDone,
		arg.DoneDate,
		arg.ID,
		arg.UserID,
	)
	var i Capture
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RawText,
		&i.MediaUrl,
		&i.MediaType,
		&i.ClassifiedAs,
		&i.TaskID,
		&i.CreatedAt,
		&i.Source,
		&i.Transcript,
		&i.TranscriptionStatus,
		&i.TranscriptionModel,
		&i.TranscriptionAttempts,
		&i.TranscribedAt,
		&i.NextTranscriptionAt,
		&i.AudioDurationSec,
		&i.MediaKey,
		&i.RemindAt,
		&i.DeletedAt,
		&i.RemindHide,
		&i.TodoAt,
		&i.DoneAt,
		&i.LinkUrl,
	)
	return i, err
}
