// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: capture_links.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const addCaptureLink = `-- name: AddCaptureLink :exec
INSERT INTO capture_links (a_id, b_id, user_id)
VALUES (
  LEAST($1::uuid, $2::uuid),
  GREATEST($1::uuid, $2::uuid),
  $3
)
ON CONFLICT (a_id, b_id) DO NOTHING
`

type AddCaptureLinkParams struct {
	X      uuid.UUID `json:"x"`
	Y      uuid.UUID `json:"y"`
	UserID uuid.UUID `json:"user_id"`
}

// Idempotent: normalises the pair (a_id < b_id) via LEAST/GREATEST so a link is
// the same regardless of direction, then no-ops on a duplicate. The caller must
// reject self-links (x = y) before calling; the CHECK constraint would otherwise
// reject a_id = b_id.
func (q *Queries) AddCaptureLink(ctx context.Context, arg AddCaptureLinkParams) error {
	_, err := q.db.Exec(ctx, addCaptureLink, arg.X, arg.Y, arg.UserID)
	return err
}

const listLinkedCaptures = `-- name: ListLinkedCaptures :many
SELECT c.id, c.user_id, c.raw_text, c.media_url, c.media_type, c.classified_as, c.task_id, c.created_at, c.source, c.transcript, c.transcription_status, c.transcription_model, c.transcription_attempts, c.transcribed_at, c.next_transcription_at, c.audio_duration_sec, c.media_key, c.remind_at, c.deleted_at, c.remind_hide, c.todo_at, c.done_at, c.link_url
FROM captures c
JOIN capture_links l
  ON (l.a_id = c.id AND l.b_id = $1::uuid)
  OR (l.b_id = c.id AND l.a_id = $1::uuid)
WHERE l.user_id = $2
  AND c.deleted_at IS NULL
ORDER BY c.created_at DESC, c.id DESC
`

type ListLinkedCapturesParams struct {
	CaptureID uuid.UUID `json:"capture_id"`
	UserID    uuid.UUID `json:"user_id"`
}

// Captures explicitly linked to a given capture, either direction. Joins captures
// and filters deleted_at IS NULL, so links to a trashed capture are hidden until
// it is restored. Newest first.
func (q *Queries) ListLinkedCaptures(ctx context.Context, arg ListLinkedCapturesParams) ([]Capture, error) {
	rows, err := q.db.Query(ctx, listLinkedCaptures, arg.CaptureID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Capture
	for rows.Next() {
		var i Capture
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.RawText,
			&i.MediaUrl,
			&i.MediaType,
			&i.ClassifiedAs,
			&i.TaskID,
			&i.CreatedAt,
			&i.Source,
			&i.Transcript,
			&i.TranscriptionStatus,
			&i.TranscriptionModel,
			&i.TranscriptionAttempts,
			&i.TranscribedAt,
			&i.NextTranscriptionAt,
			&i.AudioDurationSec,
			&i.MediaKey,
			&i.RemindAt,
			&i.DeletedAt,
			&i.RemindHide,
			&i.TodoAt,
			&i.DoneAt,
			&i.LinkUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeCaptureLink = `-- name: RemoveCaptureLink :exec
DELETE FROM capture_links
WHERE user_id = $1
  AND a_id = LEAST($2::uuid, $3::uuid)
  AND b_id = GREATEST($2::uuid, $3::uuid)
`

type RemoveCaptureLinkParams struct {
	UserID uuid.UUID `json:"user_id"`
	X      uuid.UUID `json:"x"`
	Y      uuid.UUID `json:"y"`
}

// Hard delete of the normalised pair (derived association table — see migration
// 021). user_id scoping prevents removing another user's link.
func (q *Queries) RemoveCaptureLink(ctx context.Context, arg RemoveCaptureLinkParams) error {
	_, err := q.db.Exec(ctx, removeCaptureLink, arg.UserID, arg.X, arg.Y)
	return err
}
