// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: captures.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createCapture = `-- name: CreateCapture :one
INSERT INTO captures (user_id, raw_text, media_url, media_type, classified_as, task_id)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, raw_text, media_url, media_type, classified_as, task_id, created_at
`

type CreateCaptureParams struct {
	UserID       uuid.UUID           `json:"user_id"`
	RawText      pgtype.Text         `json:"raw_text"`
	MediaUrl     pgtype.Text         `json:"media_url"`
	MediaType    CaptureMediaType    `json:"media_type"`
	ClassifiedAs CaptureClassifiedAs `json:"classified_as"`
	TaskID       pgtype.UUID         `json:"task_id"`
}

func (q *Queries) CreateCapture(ctx context.Context, arg CreateCaptureParams) (Capture, error) {
	row := q.db.QueryRow(ctx, createCapture,
		arg.UserID,
		arg.RawText,
		arg.MediaUrl,
		arg.MediaType,
		arg.ClassifiedAs,
		arg.TaskID,
	)
	var i Capture
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RawText,
		&i.MediaUrl,
		&i.MediaType,
		&i.ClassifiedAs,
		&i.TaskID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteCapture = `-- name: DeleteCapture :one
DELETE FROM captures
WHERE id = $1 AND user_id = $2
RETURNING id
`

type DeleteCaptureParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteCapture(ctx context.Context, arg DeleteCaptureParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, deleteCapture, arg.ID, arg.UserID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const listCaptures = `-- name: ListCaptures :many
SELECT id, user_id, raw_text, media_url, media_type, classified_as, task_id, created_at FROM captures
WHERE user_id = $1
  AND ($2::text IS NULL OR classified_as::text = $2::text)
ORDER BY created_at DESC
`

type ListCapturesParams struct {
	UserID       uuid.UUID   `json:"user_id"`
	ClassifiedAs pgtype.Text `json:"classified_as"`
}

func (q *Queries) ListCaptures(ctx context.Context, arg ListCapturesParams) ([]Capture, error) {
	rows, err := q.db.Query(ctx, listCaptures, arg.UserID, arg.ClassifiedAs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Capture
	for rows.Next() {
		var i Capture
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.RawText,
			&i.MediaUrl,
			&i.MediaType,
			&i.ClassifiedAs,
			&i.TaskID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCapture = `-- name: UpdateCapture :one
UPDATE captures
SET
  classified_as = CASE WHEN $1::text IS NOT NULL
                  THEN $1::capture_classified_as
                  ELSE classified_as END,
  task_id       = COALESCE($2::uuid, task_id)
WHERE id = $3 AND user_id = $4
RETURNING id, user_id, raw_text, media_url, media_type, classified_as, task_id, created_at
`

type UpdateCaptureParams struct {
	ClassifiedAs pgtype.Text `json:"classified_as"`
	TaskID       pgtype.UUID `json:"task_id"`
	ID           uuid.UUID   `json:"id"`
	UserID       uuid.UUID   `json:"user_id"`
}

func (q *Queries) UpdateCapture(ctx context.Context, arg UpdateCaptureParams) (Capture, error) {
	row := q.db.QueryRow(ctx, updateCapture,
		arg.ClassifiedAs,
		arg.TaskID,
		arg.ID,
		arg.UserID,
	)
	var i Capture
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RawText,
		&i.MediaUrl,
		&i.MediaType,
		&i.ClassifiedAs,
		&i.TaskID,
		&i.CreatedAt,
	)
	return i, err
}
