// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: capture_tokens.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createCaptureToken = `-- name: CreateCaptureToken :one
INSERT INTO capture_tokens (user_id, token_hash, name)
VALUES ($1, $2, $3)
RETURNING id, user_id, token_hash, name, last_used_at, revoked, created_at
`

type CreateCaptureTokenParams struct {
	UserID    uuid.UUID `json:"user_id"`
	TokenHash string    `json:"token_hash"`
	Name      string    `json:"name"`
}

func (q *Queries) CreateCaptureToken(ctx context.Context, arg CreateCaptureTokenParams) (CaptureToken, error) {
	row := q.db.QueryRow(ctx, createCaptureToken, arg.UserID, arg.TokenHash, arg.Name)
	var i CaptureToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.Name,
		&i.LastUsedAt,
		&i.Revoked,
		&i.CreatedAt,
	)
	return i, err
}

const getCaptureTokenByHash = `-- name: GetCaptureTokenByHash :one
SELECT id, user_id, token_hash, name, last_used_at, revoked, created_at FROM capture_tokens
WHERE token_hash = $1
  AND revoked = false
LIMIT 1
`

func (q *Queries) GetCaptureTokenByHash(ctx context.Context, tokenHash string) (CaptureToken, error) {
	row := q.db.QueryRow(ctx, getCaptureTokenByHash, tokenHash)
	var i CaptureToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.Name,
		&i.LastUsedAt,
		&i.Revoked,
		&i.CreatedAt,
	)
	return i, err
}

const listCaptureTokensByUser = `-- name: ListCaptureTokensByUser :many
SELECT id, name, last_used_at, created_at FROM capture_tokens
WHERE user_id = $1
  AND revoked = false
ORDER BY created_at DESC
`

type ListCaptureTokensByUserRow struct {
	ID         uuid.UUID          `json:"id"`
	Name       string             `json:"name"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListCaptureTokensByUser(ctx context.Context, userID uuid.UUID) ([]ListCaptureTokensByUserRow, error) {
	rows, err := q.db.Query(ctx, listCaptureTokensByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCaptureTokensByUserRow
	for rows.Next() {
		var i ListCaptureTokensByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.LastUsedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeCaptureToken = `-- name: RevokeCaptureToken :exec
UPDATE capture_tokens
SET revoked = true
WHERE id = $1
  AND user_id = $2
`

type RevokeCaptureTokenParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) RevokeCaptureToken(ctx context.Context, arg RevokeCaptureTokenParams) error {
	_, err := q.db.Exec(ctx, revokeCaptureToken, arg.ID, arg.UserID)
	return err
}

const touchCaptureTokenLastUsed = `-- name: TouchCaptureTokenLastUsed :exec
UPDATE capture_tokens
SET last_used_at = now()
WHERE id = $1
`

func (q *Queries) TouchCaptureTokenLastUsed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchCaptureTokenLastUsed, id)
	return err
}
