// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: capture_shares.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createCaptureShare = `-- name: CreateCaptureShare :one
INSERT INTO capture_shares (
  id, user_id, capture_id, secret, snapshot_raw_text, captured_at, expires_at
)
VALUES (
  $1, $2, $3,
  $4, $5, $6,
  $7
)
RETURNING id, user_id, capture_id, snapshot_raw_text, captured_at, expires_at, revoked_at, created_at, secret
`

type CreateCaptureShareParams struct {
	ID              uuid.UUID          `json:"id"`
	UserID          uuid.UUID          `json:"user_id"`
	CaptureID       uuid.UUID          `json:"capture_id"`
	Secret          string             `json:"secret"`
	SnapshotRawText string             `json:"snapshot_raw_text"`
	CapturedAt      pgtype.Timestamptz `json:"captured_at"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateCaptureShare(ctx context.Context, arg CreateCaptureShareParams) (CaptureShare, error) {
	row := q.db.QueryRow(ctx, createCaptureShare,
		arg.ID,
		arg.UserID,
		arg.CaptureID,
		arg.Secret,
		arg.SnapshotRawText,
		arg.CapturedAt,
		arg.ExpiresAt,
	)
	var i CaptureShare
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CaptureID,
		&i.SnapshotRawText,
		&i.CapturedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.Secret,
	)
	return i, err
}

const getPublicCaptureShare = `-- name: GetPublicCaptureShare :one
SELECT cs.id, cs.user_id, cs.capture_id, cs.snapshot_raw_text, cs.captured_at, cs.expires_at, cs.revoked_at, cs.created_at, cs.secret
FROM capture_shares cs
JOIN captures c ON c.id = cs.capture_id
WHERE cs.id = $1
  AND cs.revoked_at IS NULL
  AND (cs.expires_at IS NULL OR cs.expires_at > now())
  AND c.deleted_at IS NULL
`

func (q *Queries) GetPublicCaptureShare(ctx context.Context, id uuid.UUID) (CaptureShare, error) {
	row := q.db.QueryRow(ctx, getPublicCaptureShare, id)
	var i CaptureShare
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CaptureID,
		&i.SnapshotRawText,
		&i.CapturedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.Secret,
	)
	return i, err
}

const getShareableCaptureForUpdate = `-- name: GetShareableCaptureForUpdate :one
SELECT id, user_id, raw_text, media_url, media_type, classified_as, task_id, created_at, source, transcript, transcription_status, transcription_model, transcription_attempts, transcribed_at, next_transcription_at, audio_duration_sec, media_key, remind_at, deleted_at, remind_hide, todo_at, done_at, link_url
FROM captures
WHERE id = $1
  AND user_id = $2
  AND deleted_at IS NULL
  AND raw_text IS NOT NULL
  AND length(btrim(raw_text)) > 0
FOR UPDATE
`

type GetShareableCaptureForUpdateParams struct {
	CaptureID uuid.UUID `json:"capture_id"`
	UserID    uuid.UUID `json:"user_id"`
}

// Serialises share replacement for one Capture so concurrent creates cannot
// leave two unrevoked links. Text-only is intentional for the first sharing
// surface: transcripts, media, attachments, and context remain private.
func (q *Queries) GetShareableCaptureForUpdate(ctx context.Context, arg GetShareableCaptureForUpdateParams) (Capture, error) {
	row := q.db.QueryRow(ctx, getShareableCaptureForUpdate, arg.CaptureID, arg.UserID)
	var i Capture
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RawText,
		&i.MediaUrl,
		&i.MediaType,
		&i.ClassifiedAs,
		&i.TaskID,
		&i.CreatedAt,
		&i.Source,
		&i.Transcript,
		&i.TranscriptionStatus,
		&i.TranscriptionModel,
		&i.TranscriptionAttempts,
		&i.TranscribedAt,
		&i.NextTranscriptionAt,
		&i.AudioDurationSec,
		&i.MediaKey,
		&i.RemindAt,
		&i.DeletedAt,
		&i.RemindHide,
		&i.TodoAt,
		&i.DoneAt,
		&i.LinkUrl,
	)
	return i, err
}

const listCaptureSharesPage = `-- name: ListCaptureSharesPage :many
SELECT id, user_id, capture_id, snapshot_raw_text, captured_at, expires_at, revoked_at, created_at, secret
FROM capture_shares
WHERE user_id = $1
  AND revoked_at IS NULL
  AND (expires_at IS NULL OR expires_at > now())
  AND (
    $2::uuid IS NULL
    OR capture_id = $2::uuid
  )
  AND (
    $3::timestamptz IS NULL
    OR (created_at, id) < (
      $3::timestamptz,
      $4::uuid
    )
  )
ORDER BY created_at DESC, id DESC
LIMIT $5
`

type ListCaptureSharesPageParams struct {
	UserID          uuid.UUID          `json:"user_id"`
	CaptureID       pgtype.UUID        `json:"capture_id"`
	CursorCreatedAt pgtype.Timestamptz `json:"cursor_created_at"`
	CursorID        pgtype.UUID        `json:"cursor_id"`
	PageSize        int32              `json:"page_size"`
}

func (q *Queries) ListCaptureSharesPage(ctx context.Context, arg ListCaptureSharesPageParams) ([]CaptureShare, error) {
	rows, err := q.db.Query(ctx, listCaptureSharesPage,
		arg.UserID,
		arg.CaptureID,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CaptureShare
	for rows.Next() {
		var i CaptureShare
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CaptureID,
			&i.SnapshotRawText,
			&i.CapturedAt,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.CreatedAt,
			&i.Secret,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeActiveCaptureShares = `-- name: RevokeActiveCaptureShares :exec
UPDATE capture_shares
SET revoked_at = now()
WHERE capture_id = $1
  AND user_id = $2
  AND revoked_at IS NULL
`

type RevokeActiveCaptureSharesParams struct {
	CaptureID uuid.UUID `json:"capture_id"`
	UserID    uuid.UUID `json:"user_id"`
}

func (q *Queries) RevokeActiveCaptureShares(ctx context.Context, arg RevokeActiveCaptureSharesParams) error {
	_, err := q.db.Exec(ctx, revokeActiveCaptureShares, arg.CaptureID, arg.UserID)
	return err
}

const revokeCaptureShare = `-- name: RevokeCaptureShare :one
UPDATE capture_shares
SET revoked_at = now()
WHERE id = $1
  AND user_id = $2
  AND revoked_at IS NULL
RETURNING id
`

type RevokeCaptureShareParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) RevokeCaptureShare(ctx context.Context, arg RevokeCaptureShareParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, revokeCaptureShare, arg.ID, arg.UserID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
