// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: capture_attachments.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createCaptureAttachment = `-- name: CreateCaptureAttachment :one
INSERT INTO capture_attachments (
  user_id,
  capture_id,
  provider,
  provider_file_id,
  name,
  mime_type,
  size_bytes,
  web_url
)
SELECT
  $1::uuid,
  $2::uuid,
  $3::cloud_drive_provider,
  $4::text,
  $5::text,
  $6::text,
  $7::bigint,
  $8::text
FROM captures c
WHERE c.id = $2
  AND c.user_id = $1
  AND c.deleted_at IS NULL
RETURNING id, user_id, capture_id, provider, provider_file_id, name, mime_type, size_bytes, web_url, created_at, deleted_at
`

type CreateCaptureAttachmentParams struct {
	UserID         uuid.UUID          `json:"user_id"`
	CaptureID      uuid.UUID          `json:"capture_id"`
	Provider       CloudDriveProvider `json:"provider"`
	ProviderFileID string             `json:"provider_file_id"`
	Name           string             `json:"name"`
	MimeType       pgtype.Text        `json:"mime_type"`
	SizeBytes      pgtype.Int8        `json:"size_bytes"`
	WebUrl         string             `json:"web_url"`
}

func (q *Queries) CreateCaptureAttachment(ctx context.Context, arg CreateCaptureAttachmentParams) (CaptureAttachment, error) {
	row := q.db.QueryRow(ctx, createCaptureAttachment,
		arg.UserID,
		arg.CaptureID,
		arg.Provider,
		arg.ProviderFileID,
		arg.Name,
		arg.MimeType,
		arg.SizeBytes,
		arg.WebUrl,
	)
	var i CaptureAttachment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CaptureID,
		&i.Provider,
		&i.ProviderFileID,
		&i.Name,
		&i.MimeType,
		&i.SizeBytes,
		&i.WebUrl,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteCaptureAttachment = `-- name: DeleteCaptureAttachment :one
UPDATE capture_attachments ca
SET deleted_at = now()
FROM captures c
WHERE ca.id = $1
  AND ca.capture_id = $2
  AND ca.user_id = $3
  AND ca.deleted_at IS NULL
  AND c.id = ca.capture_id
  AND c.user_id = $3
  AND c.deleted_at IS NULL
RETURNING ca.id
`

type DeleteCaptureAttachmentParams struct {
	ID        uuid.UUID `json:"id"`
	CaptureID uuid.UUID `json:"capture_id"`
	UserID    uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteCaptureAttachment(ctx context.Context, arg DeleteCaptureAttachmentParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, deleteCaptureAttachment, arg.ID, arg.CaptureID, arg.UserID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const listCaptureAttachments = `-- name: ListCaptureAttachments :many
SELECT ca.id, ca.user_id, ca.capture_id, ca.provider, ca.provider_file_id, ca.name, ca.mime_type, ca.size_bytes, ca.web_url, ca.created_at, ca.deleted_at
FROM capture_attachments ca
JOIN captures c ON c.id = ca.capture_id
WHERE ca.user_id = $1
  AND ca.capture_id = $2
  AND ca.deleted_at IS NULL
  AND c.user_id = $1
  AND c.deleted_at IS NULL
ORDER BY ca.created_at DESC, ca.id DESC
`

type ListCaptureAttachmentsParams struct {
	UserID    uuid.UUID `json:"user_id"`
	CaptureID uuid.UUID `json:"capture_id"`
}

func (q *Queries) ListCaptureAttachments(ctx context.Context, arg ListCaptureAttachmentsParams) ([]CaptureAttachment, error) {
	rows, err := q.db.Query(ctx, listCaptureAttachments, arg.UserID, arg.CaptureID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CaptureAttachment
	for rows.Next() {
		var i CaptureAttachment
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CaptureID,
			&i.Provider,
			&i.ProviderFileID,
			&i.Name,
			&i.MimeType,
			&i.SizeBytes,
			&i.WebUrl,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCaptureAttachmentsByCaptureIDs = `-- name: ListCaptureAttachmentsByCaptureIDs :many
SELECT ca.id, ca.user_id, ca.capture_id, ca.provider, ca.provider_file_id, ca.name, ca.mime_type, ca.size_bytes, ca.web_url, ca.created_at, ca.deleted_at FROM capture_attachments ca
WHERE ca.user_id = $1
  AND ca.capture_id = ANY($2::uuid[])
  AND ca.deleted_at IS NULL
ORDER BY ca.created_at DESC, ca.id DESC
`

type ListCaptureAttachmentsByCaptureIDsParams struct {
	UserID     uuid.UUID   `json:"user_id"`
	CaptureIds []uuid.UUID `json:"capture_ids"`
}

// Batch fetch for the capture page listing: one query for a whole page of
// captures instead of one per capture. No captures join needed — the page
// query already established ownership and liveness of every id passed in.
func (q *Queries) ListCaptureAttachmentsByCaptureIDs(ctx context.Context, arg ListCaptureAttachmentsByCaptureIDsParams) ([]CaptureAttachment, error) {
	rows, err := q.db.Query(ctx, listCaptureAttachmentsByCaptureIDs, arg.UserID, arg.CaptureIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CaptureAttachment
	for rows.Next() {
		var i CaptureAttachment
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CaptureID,
			&i.Provider,
			&i.ProviderFileID,
			&i.Name,
			&i.MimeType,
			&i.SizeBytes,
			&i.WebUrl,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertCaptureAttachment = `-- name: UpsertCaptureAttachment :one
INSERT INTO capture_attachments (
  user_id,
  capture_id,
  provider,
  provider_file_id,
  name,
  mime_type,
  size_bytes,
  web_url
)
SELECT
  $1::uuid,
  $2::uuid,
  $3::cloud_drive_provider,
  $4::text,
  $5::text,
  $6::text,
  $7::bigint,
  $8::text
FROM captures c
WHERE c.id = $2
  AND c.user_id = $1
  AND c.deleted_at IS NULL
ON CONFLICT (capture_id, provider, provider_file_id)
WHERE deleted_at IS NULL
DO UPDATE SET
  name = EXCLUDED.name,
  mime_type = EXCLUDED.mime_type,
  size_bytes = EXCLUDED.size_bytes,
  web_url = EXCLUDED.web_url
RETURNING id, user_id, capture_id, provider, provider_file_id, name, mime_type, size_bytes, web_url, created_at, deleted_at
`

type UpsertCaptureAttachmentParams struct {
	UserID         uuid.UUID          `json:"user_id"`
	CaptureID      uuid.UUID          `json:"capture_id"`
	Provider       CloudDriveProvider `json:"provider"`
	ProviderFileID string             `json:"provider_file_id"`
	Name           string             `json:"name"`
	MimeType       pgtype.Text        `json:"mime_type"`
	SizeBytes      pgtype.Int8        `json:"size_bytes"`
	WebUrl         string             `json:"web_url"`
}

// Used only by the atomic create-with-attachment operation. A lost response can
// be retried with the same Capture id and provider file id without duplicating
// either row.
func (q *Queries) UpsertCaptureAttachment(ctx context.Context, arg UpsertCaptureAttachmentParams) (CaptureAttachment, error) {
	row := q.db.QueryRow(ctx, upsertCaptureAttachment,
		arg.UserID,
		arg.CaptureID,
		arg.Provider,
		arg.ProviderFileID,
		arg.Name,
		arg.MimeType,
		arg.SizeBytes,
		arg.WebUrl,
	)
	var i CaptureAttachment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CaptureID,
		&i.Provider,
		&i.ProviderFileID,
		&i.Name,
		&i.MimeType,
		&i.SizeBytes,
		&i.WebUrl,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}
