// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: imports.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const claimMarkdownImportOperation = `-- name: ClaimMarkdownImportOperation :one
WITH expired AS (
  DELETE FROM markdown_import_operations
  WHERE id IN (
    SELECT id
    FROM markdown_import_operations
    WHERE status IN ('completed', 'failed', 'undone')
      AND COALESCE(undone_at, completed_at, created_at) < now() - interval '30 days'
    ORDER BY COALESCE(undone_at, completed_at, created_at)
    LIMIT 1000
  )
)
INSERT INTO markdown_import_operations (
  id, user_id, input_hash, status, lease_until, claim_token
)
VALUES (
  $1::uuid,
  $2::uuid,
  $3::text,
  'processing',
  now() + interval '2 hours',
  $4::uuid
)
ON CONFLICT (id) DO UPDATE
SET status = 'processing',
    lease_until = now() + interval '2 hours',
    claim_token = excluded.claim_token,
    last_error = NULL
WHERE markdown_import_operations.user_id = excluded.user_id
  AND markdown_import_operations.input_hash = excluded.input_hash
  AND (
    markdown_import_operations.status = 'failed'
    OR (
      markdown_import_operations.status = 'processing'
      AND markdown_import_operations.lease_until <= now()
    )
  )
RETURNING id, user_id, input_hash, claim_token, status, lease_until, result, created_capture_ids, last_error, created_at, completed_at, undone_at
`

type ClaimMarkdownImportOperationParams struct {
	ID         uuid.UUID `json:"id"`
	UserID     uuid.UUID `json:"user_id"`
	InputHash  string    `json:"input_hash"`
	ClaimToken uuid.UUID `json:"claim_token"`
}

func (q *Queries) ClaimMarkdownImportOperation(ctx context.Context, arg ClaimMarkdownImportOperationParams) (MarkdownImportOperation, error) {
	row := q.db.QueryRow(ctx, claimMarkdownImportOperation,
		arg.ID,
		arg.UserID,
		arg.InputHash,
		arg.ClaimToken,
	)
	var i MarkdownImportOperation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.InputHash,
		&i.ClaimToken,
		&i.Status,
		&i.LeaseUntil,
		&i.Result,
		&i.CreatedCaptureIds,
		&i.LastError,
		&i.CreatedAt,
		&i.CompletedAt,
		&i.UndoneAt,
	)
	return i, err
}

const completeMarkdownImportOperation = `-- name: CompleteMarkdownImportOperation :execrows
UPDATE markdown_import_operations
SET status = 'completed',
    lease_until = now(),
    result = $1::jsonb,
    created_capture_ids = $2::uuid[],
    completed_at = now(),
    undone_at = NULL,
    last_error = NULL
WHERE id = $3::uuid
  AND user_id = $4::uuid
  AND input_hash = $5::text
  AND claim_token = $6::uuid
  AND status = 'processing'
`

type CompleteMarkdownImportOperationParams struct {
	Result            []byte      `json:"result"`
	CreatedCaptureIds []uuid.UUID `json:"created_capture_ids"`
	ID                uuid.UUID   `json:"id"`
	UserID            uuid.UUID   `json:"user_id"`
	InputHash         string      `json:"input_hash"`
	ClaimToken        uuid.UUID   `json:"claim_token"`
}

func (q *Queries) CompleteMarkdownImportOperation(ctx context.Context, arg CompleteMarkdownImportOperationParams) (int64, error) {
	result, err := q.db.Exec(ctx, completeMarkdownImportOperation,
		arg.Result,
		arg.CreatedCaptureIds,
		arg.ID,
		arg.UserID,
		arg.InputHash,
		arg.ClaimToken,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const failMarkdownImportOperation = `-- name: FailMarkdownImportOperation :execrows
UPDATE markdown_import_operations
SET status = 'failed',
    lease_until = now(),
    last_error = $1::text
WHERE id = $2::uuid
  AND user_id = $3::uuid
  AND input_hash = $4::text
  AND claim_token = $5::uuid
  AND status = 'processing'
`

type FailMarkdownImportOperationParams struct {
	LastError  string    `json:"last_error"`
	ID         uuid.UUID `json:"id"`
	UserID     uuid.UUID `json:"user_id"`
	InputHash  string    `json:"input_hash"`
	ClaimToken uuid.UUID `json:"claim_token"`
}

func (q *Queries) FailMarkdownImportOperation(ctx context.Context, arg FailMarkdownImportOperationParams) (int64, error) {
	result, err := q.db.Exec(ctx, failMarkdownImportOperation,
		arg.LastError,
		arg.ID,
		arg.UserID,
		arg.InputHash,
		arg.ClaimToken,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getImportOperation = `-- name: GetImportOperation :one
SELECT id, user_id, input_hash, claim_token, status, lease_until, result, created_capture_ids, last_error, created_at, completed_at, undone_at FROM markdown_import_operations
WHERE id = $1::uuid
`

func (q *Queries) GetImportOperation(ctx context.Context, id uuid.UUID) (MarkdownImportOperation, error) {
	row := q.db.QueryRow(ctx, getImportOperation, id)
	var i MarkdownImportOperation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.InputHash,
		&i.ClaimToken,
		&i.Status,
		&i.LeaseUntil,
		&i.Result,
		&i.CreatedCaptureIds,
		&i.LastError,
		&i.CreatedAt,
		&i.CompletedAt,
		&i.UndoneAt,
	)
	return i, err
}

const markMarkdownImportUndone = `-- name: MarkMarkdownImportUndone :execrows
UPDATE markdown_import_operations
SET status = 'undone',
    lease_until = now(),
    undone_at = now()
WHERE id = $1::uuid
  AND user_id = $2::uuid
  AND status = 'completed'
`

type MarkMarkdownImportUndoneParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) MarkMarkdownImportUndone(ctx context.Context, arg MarkMarkdownImportUndoneParams) (int64, error) {
	result, err := q.db.Exec(ctx, markMarkdownImportUndone, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const softDeleteMarkdownImportCaptures = `-- name: SoftDeleteMarkdownImportCaptures :many
UPDATE captures
SET deleted_at = now()
WHERE user_id = $1::uuid
  AND id = ANY($2::uuid[])
  AND deleted_at IS NULL
RETURNING id
`

type SoftDeleteMarkdownImportCapturesParams struct {
	UserID     uuid.UUID   `json:"user_id"`
	CaptureIds []uuid.UUID `json:"capture_ids"`
}

func (q *Queries) SoftDeleteMarkdownImportCaptures(ctx context.Context, arg SoftDeleteMarkdownImportCapturesParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, softDeleteMarkdownImportCaptures, arg.UserID, arg.CaptureIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
