// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: log_entries.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createLogEntry = `-- name: CreateLogEntry :one
INSERT INTO log_entries (user_id, task_id, body)
VALUES ($1, $2, $3)
RETURNING id, user_id, task_id, body, created_at, deleted_at
`

type CreateLogEntryParams struct {
	UserID uuid.UUID   `json:"user_id"`
	TaskID pgtype.UUID `json:"task_id"`
	Body   string      `json:"body"`
}

func (q *Queries) CreateLogEntry(ctx context.Context, arg CreateLogEntryParams) (LogEntry, error) {
	row := q.db.QueryRow(ctx, createLogEntry, arg.UserID, arg.TaskID, arg.Body)
	var i LogEntry
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TaskID,
		&i.Body,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteLogEntry = `-- name: DeleteLogEntry :one
UPDATE log_entries
SET deleted_at = now()
WHERE id = $1 AND user_id = $2 AND deleted_at IS NULL
RETURNING id
`

type DeleteLogEntryParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteLogEntry(ctx context.Context, arg DeleteLogEntryParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, deleteLogEntry, arg.ID, arg.UserID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const listLogEntries = `-- name: ListLogEntries :many
SELECT id, user_id, task_id, body, created_at, deleted_at FROM log_entries
WHERE user_id = $1
  AND deleted_at IS NULL
  AND ($2::uuid IS NULL OR task_id = $2::uuid)
ORDER BY created_at DESC
`

type ListLogEntriesParams struct {
	UserID uuid.UUID   `json:"user_id"`
	TaskID pgtype.UUID `json:"task_id"`
}

func (q *Queries) ListLogEntries(ctx context.Context, arg ListLogEntriesParams) ([]LogEntry, error) {
	rows, err := q.db.Query(ctx, listLogEntries, arg.UserID, arg.TaskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LogEntry
	for rows.Next() {
		var i LogEntry
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TaskID,
			&i.Body,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLogEntry = `-- name: UpdateLogEntry :one
UPDATE log_entries
SET body = $1
WHERE id = $2 AND user_id = $3 AND deleted_at IS NULL
RETURNING id, user_id, task_id, body, created_at, deleted_at
`

type UpdateLogEntryParams struct {
	Body   string    `json:"body"`
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) UpdateLogEntry(ctx context.Context, arg UpdateLogEntryParams) (LogEntry, error) {
	row := q.db.QueryRow(ctx, updateLogEntry, arg.Body, arg.ID, arg.UserID)
	var i LogEntry
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TaskID,
		&i.Body,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}
