// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: media_deletions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimCaptureMediaDeletion = `-- name: ClaimCaptureMediaDeletion :one
WITH candidate AS (
    SELECT object_key
    FROM capture_media_deletions
    WHERE next_attempt_at <= now()
      AND (lease_until IS NULL OR lease_until <= now())
    ORDER BY next_attempt_at, created_at, object_key
    FOR UPDATE SKIP LOCKED
    LIMIT 1
)
UPDATE capture_media_deletions AS deletion
SET lease_until = now() + interval '5 minutes'
FROM candidate
WHERE deletion.object_key = candidate.object_key
RETURNING deletion.object_key, deletion.attempts, deletion.next_attempt_at, deletion.lease_until, deletion.last_error, deletion.created_at
`

func (q *Queries) ClaimCaptureMediaDeletion(ctx context.Context) (CaptureMediaDeletion, error) {
	row := q.db.QueryRow(ctx, claimCaptureMediaDeletion)
	var i CaptureMediaDeletion
	err := row.Scan(
		&i.ObjectKey,
		&i.Attempts,
		&i.NextAttemptAt,
		&i.LeaseUntil,
		&i.LastError,
		&i.CreatedAt,
	)
	return i, err
}

const completeCaptureMediaDeletion = `-- name: CompleteCaptureMediaDeletion :execrows
DELETE FROM capture_media_deletions
WHERE object_key = $1
  AND lease_until = $2
`

type CompleteCaptureMediaDeletionParams struct {
	ObjectKey  string             `json:"object_key"`
	LeaseUntil pgtype.Timestamptz `json:"lease_until"`
}

func (q *Queries) CompleteCaptureMediaDeletion(ctx context.Context, arg CompleteCaptureMediaDeletionParams) (int64, error) {
	result, err := q.db.Exec(ctx, completeCaptureMediaDeletion, arg.ObjectKey, arg.LeaseUntil)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const failCaptureMediaDeletion = `-- name: FailCaptureMediaDeletion :execrows
UPDATE capture_media_deletions
SET attempts = attempts + 1,
    next_attempt_at = now()
        + LEAST(
            interval '1 day',
            interval '1 minute' * power(2, LEAST(attempts, 10))
        ),
    lease_until = NULL,
    last_error = $3
WHERE object_key = $1
  AND lease_until = $2
`

type FailCaptureMediaDeletionParams struct {
	ObjectKey  string             `json:"object_key"`
	LeaseUntil pgtype.Timestamptz `json:"lease_until"`
	LastError  pgtype.Text        `json:"last_error"`
}

func (q *Queries) FailCaptureMediaDeletion(ctx context.Context, arg FailCaptureMediaDeletionParams) (int64, error) {
	result, err := q.db.Exec(ctx, failCaptureMediaDeletion, arg.ObjectKey, arg.LeaseUntil, arg.LastError)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const nextCaptureMediaDeletionAt = `-- name: NextCaptureMediaDeletionAt :one
SELECT min(
    CASE
        WHEN lease_until IS NOT NULL AND lease_until > next_attempt_at
            THEN lease_until
        ELSE next_attempt_at
    END
)::timestamptz
FROM capture_media_deletions
`

func (q *Queries) NextCaptureMediaDeletionAt(ctx context.Context) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, nextCaptureMediaDeletionAt)
	var column_1 pgtype.Timestamptz
	err := row.Scan(&column_1)
	return column_1, err
}
