// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type CaptureClassifiedAs string

const (
	CaptureClassifiedAsTask         CaptureClassifiedAs = "task"
	CaptureClassifiedAsIdea         CaptureClassifiedAs = "idea"
	CaptureClassifiedAsRoutine      CaptureClassifiedAs = "routine"
	CaptureClassifiedAsLog          CaptureClassifiedAs = "log"
	CaptureClassifiedAsUnclassified CaptureClassifiedAs = "unclassified"
)

func (e *CaptureClassifiedAs) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CaptureClassifiedAs(s)
	case string:
		*e = CaptureClassifiedAs(s)
	default:
		return fmt.Errorf("unsupported scan type for CaptureClassifiedAs: %T", src)
	}
	return nil
}

type NullCaptureClassifiedAs struct {
	CaptureClassifiedAs CaptureClassifiedAs `json:"capture_classified_as"`
	Valid               bool                `json:"valid"` // Valid is true if CaptureClassifiedAs is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCaptureClassifiedAs) Scan(value interface{}) error {
	if value == nil {
		ns.CaptureClassifiedAs, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CaptureClassifiedAs.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCaptureClassifiedAs) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CaptureClassifiedAs), nil
}

type CaptureMediaType string

const (
	CaptureMediaTypeText  CaptureMediaType = "text"
	CaptureMediaTypeImage CaptureMediaType = "image"
	CaptureMediaTypeAudio CaptureMediaType = "audio"
)

func (e *CaptureMediaType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CaptureMediaType(s)
	case string:
		*e = CaptureMediaType(s)
	default:
		return fmt.Errorf("unsupported scan type for CaptureMediaType: %T", src)
	}
	return nil
}

type NullCaptureMediaType struct {
	CaptureMediaType CaptureMediaType `json:"capture_media_type"`
	Valid            bool             `json:"valid"` // Valid is true if CaptureMediaType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCaptureMediaType) Scan(value interface{}) error {
	if value == nil {
		ns.CaptureMediaType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CaptureMediaType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCaptureMediaType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CaptureMediaType), nil
}

type CloudDriveProvider string

const (
	CloudDriveProviderGoogleDrive CloudDriveProvider = "google_drive"
	CloudDriveProviderOnedrive    CloudDriveProvider = "onedrive"
	CloudDriveProviderDropbox     CloudDriveProvider = "dropbox"
)

func (e *CloudDriveProvider) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CloudDriveProvider(s)
	case string:
		*e = CloudDriveProvider(s)
	default:
		return fmt.Errorf("unsupported scan type for CloudDriveProvider: %T", src)
	}
	return nil
}

type NullCloudDriveProvider struct {
	CloudDriveProvider CloudDriveProvider `json:"cloud_drive_provider"`
	Valid              bool               `json:"valid"` // Valid is true if CloudDriveProvider is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCloudDriveProvider) Scan(value interface{}) error {
	if value == nil {
		ns.CloudDriveProvider, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CloudDriveProvider.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCloudDriveProvider) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CloudDriveProvider), nil
}

type TaskStatus string

const (
	TaskStatusTodo       TaskStatus = "todo"
	TaskStatusInProgress TaskStatus = "in_progress"
	TaskStatusDone       TaskStatus = "done"
	TaskStatusArchived   TaskStatus = "archived"
)

func (e *TaskStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TaskStatus(s)
	case string:
		*e = TaskStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for TaskStatus: %T", src)
	}
	return nil
}

type NullTaskStatus struct {
	TaskStatus TaskStatus `json:"task_status"`
	Valid      bool       `json:"valid"` // Valid is true if TaskStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTaskStatus) Scan(value interface{}) error {
	if value == nil {
		ns.TaskStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TaskStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTaskStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TaskStatus), nil
}

type TaskType string

const (
	TaskTypeTask    TaskType = "task"
	TaskTypeIdea    TaskType = "idea"
	TaskTypeRoutine TaskType = "routine"
	TaskTypeLog     TaskType = "log"
)

func (e *TaskType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TaskType(s)
	case string:
		*e = TaskType(s)
	default:
		return fmt.Errorf("unsupported scan type for TaskType: %T", src)
	}
	return nil
}

type NullTaskType struct {
	TaskType TaskType `json:"task_type"`
	Valid    bool     `json:"valid"` // Valid is true if TaskType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTaskType) Scan(value interface{}) error {
	if value == nil {
		ns.TaskType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TaskType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTaskType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TaskType), nil
}

type TranscriptionStatus string

const (
	TranscriptionStatusNone       TranscriptionStatus = "none"
	TranscriptionStatusPending    TranscriptionStatus = "pending"
	TranscriptionStatusProcessing TranscriptionStatus = "processing"
	TranscriptionStatusCompleted  TranscriptionStatus = "completed"
	TranscriptionStatusFailed     TranscriptionStatus = "failed"
	TranscriptionStatusSkipped    TranscriptionStatus = "skipped"
)

func (e *TranscriptionStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TranscriptionStatus(s)
	case string:
		*e = TranscriptionStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for TranscriptionStatus: %T", src)
	}
	return nil
}

type NullTranscriptionStatus struct {
	TranscriptionStatus TranscriptionStatus `json:"transcription_status"`
	Valid               bool                `json:"valid"` // Valid is true if TranscriptionStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTranscriptionStatus) Scan(value interface{}) error {
	if value == nil {
		ns.TranscriptionStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TranscriptionStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTranscriptionStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TranscriptionStatus), nil
}

type ArchiveImportOperation struct {
	ID          uuid.UUID          `json:"id"`
	UserID      uuid.UUID          `json:"user_id"`
	ArchiveHash string             `json:"archive_hash"`
	ClaimToken  uuid.UUID          `json:"claim_token"`
	Status      string             `json:"status"`
	LeaseUntil  pgtype.Timestamptz `json:"lease_until"`
	IDMap       []byte             `json:"id_map"`
	Result      []byte             `json:"result"`
	LastError   pgtype.Text        `json:"last_error"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	CompletedAt pgtype.Timestamptz `json:"completed_at"`
}

type ArchivedLogEntry struct {
	ID          uuid.UUID          `json:"id"`
	UserID      uuid.UUID          `json:"user_id"`
	TaskID      pgtype.UUID        `json:"task_id"`
	Body        string             `json:"body"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
	TimeBlockID pgtype.UUID        `json:"time_block_id"`
}

type ArchivedProject struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	Name      string             `json:"name"`
	Color     string             `json:"color"`
	Archived  bool               `json:"archived"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type ArchivedPublicShare struct {
	ID        uuid.UUID          `json:"id"`
	ReportID  uuid.UUID          `json:"report_id"`
	Slug      string             `json:"slug"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UserID    uuid.UUID          `json:"user_id"`
}

type ArchivedTask struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	ProjectID pgtype.UUID        `json:"project_id"`
	Title     string             `json:"title"`
	Type      TaskType           `json:"type"`
	Status    TaskStatus         `json:"status"`
	DueAt     pgtype.Timestamptz `json:"due_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
	MediaUrl  pgtype.Text        `json:"media_url"`
	MediaType pgtype.Text        `json:"media_type"`
	StartAt   pgtype.Timestamptz `json:"start_at"`
}

type ArchivedTimeBlock struct {
	ID          uuid.UUID          `json:"id"`
	UserID      uuid.UUID          `json:"user_id"`
	TaskID      pgtype.UUID        `json:"task_id"`
	StartedAt   pgtype.Timestamptz `json:"started_at"`
	EndedAt     pgtype.Timestamptz `json:"ended_at"`
	DurationSec pgtype.Int4        `json:"duration_sec"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
	InputMode   string             `json:"input_mode"`
}

type ArchivedWeeklyReport struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	WeekStart pgtype.Date        `json:"week_start"`
	Data      []byte             `json:"data"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type AuthEphemeralState struct {
	Purpose   string             `json:"purpose"`
	KeyHash   []byte             `json:"key_hash"`
	Payload   []byte             `json:"payload"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type AuthRateLimit struct {
	Scope           string             `json:"scope"`
	SubjectHash     []byte             `json:"subject_hash"`
	Attempts        int32              `json:"attempts"`
	WindowStartedAt pgtype.Timestamptz `json:"window_started_at"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
}

type Capture struct {
	ID                    uuid.UUID           `json:"id"`
	UserID                uuid.UUID           `json:"user_id"`
	RawText               pgtype.Text         `json:"raw_text"`
	MediaUrl              pgtype.Text         `json:"media_url"`
	MediaType             CaptureMediaType    `json:"media_type"`
	ClassifiedAs          CaptureClassifiedAs `json:"classified_as"`
	TaskID                pgtype.UUID         `json:"task_id"`
	CreatedAt             pgtype.Timestamptz  `json:"created_at"`
	Source                string              `json:"source"`
	Transcript            pgtype.Text         `json:"transcript"`
	TranscriptionStatus   TranscriptionStatus `json:"transcription_status"`
	TranscriptionModel    pgtype.Text         `json:"transcription_model"`
	TranscriptionAttempts int32               `json:"transcription_attempts"`
	TranscribedAt         pgtype.Timestamptz  `json:"transcribed_at"`
	NextTranscriptionAt   pgtype.Timestamptz  `json:"next_transcription_at"`
	AudioDurationSec      pgtype.Int4         `json:"audio_duration_sec"`
	MediaKey              pgtype.Text         `json:"media_key"`
	RemindAt              pgtype.Timestamptz  `json:"remind_at"`
	DeletedAt             pgtype.Timestamptz  `json:"deleted_at"`
	RemindHide            bool                `json:"remind_hide"`
	TodoAt                pgtype.Timestamptz  `json:"todo_at"`
	DoneAt                pgtype.Timestamptz  `json:"done_at"`
	LinkUrl               pgtype.Text         `json:"link_url"`
}

type CaptureAttachment struct {
	ID             uuid.UUID          `json:"id"`
	UserID         uuid.UUID          `json:"user_id"`
	CaptureID      uuid.UUID          `json:"capture_id"`
	Provider       CloudDriveProvider `json:"provider"`
	ProviderFileID string             `json:"provider_file_id"`
	Name           string             `json:"name"`
	MimeType       pgtype.Text        `json:"mime_type"`
	SizeBytes      pgtype.Int8        `json:"size_bytes"`
	WebUrl         string             `json:"web_url"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	DeletedAt      pgtype.Timestamptz `json:"deleted_at"`
}

type CaptureEmbedding struct {
	CaptureID  uuid.UUID          `json:"capture_id"`
	UserID     uuid.UUID          `json:"user_id"`
	Embedding  []byte             `json:"embedding"`
	Model      string             `json:"model"`
	EmbedV     int32              `json:"embed_v"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	SourceHash pgtype.Text        `json:"source_hash"`
	ChunkIdx   int32              `json:"chunk_idx"`
	ChunkText  pgtype.Text        `json:"chunk_text"`
}

type CaptureLink struct {
	AID       uuid.UUID          `json:"a_id"`
	BID       uuid.UUID          `json:"b_id"`
	UserID    uuid.UUID          `json:"user_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type CaptureMediaDeletion struct {
	ObjectKey     string             `json:"object_key"`
	Attempts      int32              `json:"attempts"`
	NextAttemptAt pgtype.Timestamptz `json:"next_attempt_at"`
	LeaseUntil    pgtype.Timestamptz `json:"lease_until"`
	LastError     pgtype.Text        `json:"last_error"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type CaptureMetadatum struct {
	CaptureID  uuid.UUID          `json:"capture_id"`
	UserID     uuid.UUID          `json:"user_id"`
	Data       []byte             `json:"data"`
	ExtractV   int32              `json:"extract_v"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	SourceHash pgtype.Text        `json:"source_hash"`
}

type CaptureShare struct {
	ID              uuid.UUID          `json:"id"`
	UserID          uuid.UUID          `json:"user_id"`
	CaptureID       uuid.UUID          `json:"capture_id"`
	SnapshotRawText string             `json:"snapshot_raw_text"`
	CapturedAt      pgtype.Timestamptz `json:"captured_at"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
	RevokedAt       pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	Secret          string             `json:"secret"`
}

type CaptureToken struct {
	ID         uuid.UUID          `json:"id"`
	UserID     uuid.UUID          `json:"user_id"`
	TokenHash  string             `json:"token_hash"`
	Name       string             `json:"name"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
	Revoked    bool               `json:"revoked"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type CaptureUploadOperation struct {
	ID          uuid.UUID          `json:"id"`
	CaptureID   uuid.UUID          `json:"capture_id"`
	UserID      uuid.UUID          `json:"user_id"`
	RequestHash string             `json:"request_hash"`
	LeaseUntil  pgtype.Timestamptz `json:"lease_until"`
	CompletedAt pgtype.Timestamptz `json:"completed_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type CaptureWebhook struct {
	ID                uuid.UUID          `json:"id"`
	UserID            uuid.UUID          `json:"user_id"`
	Name              string             `json:"name"`
	TargetUrl         string             `json:"target_url"`
	Keywords          []string           `json:"keywords"`
	SemanticQuery     pgtype.Text        `json:"semantic_query"`
	SemanticThreshold float64            `json:"semantic_threshold"`
	PayloadTemplate   string             `json:"payload_template"`
	Enabled           bool               `json:"enabled"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	DeletedAt         pgtype.Timestamptz `json:"deleted_at"`
}

type LogEntry struct {
	ID          uuid.UUID          `json:"id"`
	UserID      uuid.UUID          `json:"user_id"`
	TaskID      pgtype.UUID        `json:"task_id"`
	Body        string             `json:"body"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
	TimeBlockID pgtype.UUID        `json:"time_block_id"`
}

type MarkdownImportOperation struct {
	ID                uuid.UUID          `json:"id"`
	UserID            uuid.UUID          `json:"user_id"`
	InputHash         string             `json:"input_hash"`
	ClaimToken        uuid.UUID          `json:"claim_token"`
	Status            string             `json:"status"`
	LeaseUntil        pgtype.Timestamptz `json:"lease_until"`
	Result            []byte             `json:"result"`
	CreatedCaptureIds []uuid.UUID        `json:"created_capture_ids"`
	LastError         pgtype.Text        `json:"last_error"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	CompletedAt       pgtype.Timestamptz `json:"completed_at"`
	UndoneAt          pgtype.Timestamptz `json:"undone_at"`
}

type OauthAccount struct {
	ID         uuid.UUID          `json:"id"`
	UserID     uuid.UUID          `json:"user_id"`
	Provider   string             `json:"provider"`
	ProviderID string             `json:"provider_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Passkey struct {
	ID           uuid.UUID          `json:"id"`
	UserID       uuid.UUID          `json:"user_id"`
	CredentialID []byte             `json:"credential_id"`
	PublicKey    []byte             `json:"public_key"`
	Aaguid       []byte             `json:"aaguid"`
	SignCount    int64              `json:"sign_count"`
	Name         string             `json:"name"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type Project struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	Name      string             `json:"name"`
	Color     string             `json:"color"`
	Archived  bool               `json:"archived"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type PublicShare struct {
	ID        uuid.UUID          `json:"id"`
	ReportID  uuid.UUID          `json:"report_id"`
	Slug      string             `json:"slug"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type RagConfig struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

type RecoveryCode struct {
	ID       uuid.UUID `json:"id"`
	UserID   uuid.UUID `json:"user_id"`
	CodeHash string    `json:"code_hash"`
	Used     bool      `json:"used"`
}

type RefreshToken struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	Revoked   bool               `json:"revoked"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type RetrievalDismissal struct {
	UserID    uuid.UUID          `json:"user_id"`
	Surface   string             `json:"surface"`
	QueryHash []byte             `json:"query_hash"`
	AnchorID  pgtype.UUID        `json:"anchor_id"`
	TargetID  uuid.UUID          `json:"target_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	QueryText pgtype.Text        `json:"query_text"`
}

type Task struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	ProjectID pgtype.UUID        `json:"project_id"`
	Title     string             `json:"title"`
	Type      TaskType           `json:"type"`
	Status    TaskStatus         `json:"status"`
	DueAt     pgtype.Timestamptz `json:"due_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
	MediaUrl  pgtype.Text        `json:"media_url"`
	MediaType pgtype.Text        `json:"media_type"`
	StartAt   pgtype.Timestamptz `json:"start_at"`
}

type TimeBlock struct {
	ID          uuid.UUID          `json:"id"`
	UserID      uuid.UUID          `json:"user_id"`
	TaskID      pgtype.UUID        `json:"task_id"`
	StartedAt   pgtype.Timestamptz `json:"started_at"`
	EndedAt     pgtype.Timestamptz `json:"ended_at"`
	DurationSec pgtype.Int4        `json:"duration_sec"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
	InputMode   string             `json:"input_mode"`
}

type User struct {
	ID                   uuid.UUID          `json:"id"`
	Email                string             `json:"email"`
	PasswordHash         pgtype.Text        `json:"password_hash"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	EmailVerified        bool               `json:"email_verified"`
	EmailVerifyToken     pgtype.Text        `json:"email_verify_token"`
	PasswordResetToken   pgtype.Text        `json:"password_reset_token"`
	PasswordResetExpires pgtype.Timestamptz `json:"password_reset_expires"`
	TotpSecret           pgtype.Text        `json:"totp_secret"`
	TotpEnabled          bool               `json:"totp_enabled"`
}

type WeeklyReport struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	WeekStart pgtype.Date        `json:"week_start"`
	Data      []byte             `json:"data"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}
