// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type CaptureClassifiedAs string

const (
	CaptureClassifiedAsTask         CaptureClassifiedAs = "task"
	CaptureClassifiedAsIdea         CaptureClassifiedAs = "idea"
	CaptureClassifiedAsRoutine      CaptureClassifiedAs = "routine"
	CaptureClassifiedAsLog          CaptureClassifiedAs = "log"
	CaptureClassifiedAsUnclassified CaptureClassifiedAs = "unclassified"
)

func (e *CaptureClassifiedAs) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CaptureClassifiedAs(s)
	case string:
		*e = CaptureClassifiedAs(s)
	default:
		return fmt.Errorf("unsupported scan type for CaptureClassifiedAs: %T", src)
	}
	return nil
}

type NullCaptureClassifiedAs struct {
	CaptureClassifiedAs CaptureClassifiedAs `json:"capture_classified_as"`
	Valid               bool                `json:"valid"` // Valid is true if CaptureClassifiedAs is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCaptureClassifiedAs) Scan(value interface{}) error {
	if value == nil {
		ns.CaptureClassifiedAs, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CaptureClassifiedAs.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCaptureClassifiedAs) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CaptureClassifiedAs), nil
}

type CaptureMediaType string

const (
	CaptureMediaTypeText  CaptureMediaType = "text"
	CaptureMediaTypeImage CaptureMediaType = "image"
	CaptureMediaTypeAudio CaptureMediaType = "audio"
)

func (e *CaptureMediaType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CaptureMediaType(s)
	case string:
		*e = CaptureMediaType(s)
	default:
		return fmt.Errorf("unsupported scan type for CaptureMediaType: %T", src)
	}
	return nil
}

type NullCaptureMediaType struct {
	CaptureMediaType CaptureMediaType `json:"capture_media_type"`
	Valid            bool             `json:"valid"` // Valid is true if CaptureMediaType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCaptureMediaType) Scan(value interface{}) error {
	if value == nil {
		ns.CaptureMediaType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CaptureMediaType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCaptureMediaType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CaptureMediaType), nil
}

type TaskStatus string

const (
	TaskStatusTodo       TaskStatus = "todo"
	TaskStatusInProgress TaskStatus = "in_progress"
	TaskStatusDone       TaskStatus = "done"
	TaskStatusArchived   TaskStatus = "archived"
)

func (e *TaskStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TaskStatus(s)
	case string:
		*e = TaskStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for TaskStatus: %T", src)
	}
	return nil
}

type NullTaskStatus struct {
	TaskStatus TaskStatus `json:"task_status"`
	Valid      bool       `json:"valid"` // Valid is true if TaskStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTaskStatus) Scan(value interface{}) error {
	if value == nil {
		ns.TaskStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TaskStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTaskStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TaskStatus), nil
}

type TaskType string

const (
	TaskTypeTask    TaskType = "task"
	TaskTypeIdea    TaskType = "idea"
	TaskTypeRoutine TaskType = "routine"
	TaskTypeLog     TaskType = "log"
)

func (e *TaskType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TaskType(s)
	case string:
		*e = TaskType(s)
	default:
		return fmt.Errorf("unsupported scan type for TaskType: %T", src)
	}
	return nil
}

type NullTaskType struct {
	TaskType TaskType `json:"task_type"`
	Valid    bool     `json:"valid"` // Valid is true if TaskType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTaskType) Scan(value interface{}) error {
	if value == nil {
		ns.TaskType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TaskType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTaskType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TaskType), nil
}

type Capture struct {
	ID           uuid.UUID           `json:"id"`
	UserID       uuid.UUID           `json:"user_id"`
	RawText      pgtype.Text         `json:"raw_text"`
	MediaUrl     pgtype.Text         `json:"media_url"`
	MediaType    CaptureMediaType    `json:"media_type"`
	ClassifiedAs CaptureClassifiedAs `json:"classified_as"`
	TaskID       pgtype.UUID         `json:"task_id"`
	CreatedAt    pgtype.Timestamptz  `json:"created_at"`
	Source       string              `json:"source"`
}

type LogEntry struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	TaskID    pgtype.UUID        `json:"task_id"`
	Body      string             `json:"body"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

type OauthAccount struct {
	ID         uuid.UUID          `json:"id"`
	UserID     uuid.UUID          `json:"user_id"`
	Provider   string             `json:"provider"`
	ProviderID string             `json:"provider_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Passkey struct {
	ID           uuid.UUID          `json:"id"`
	UserID       uuid.UUID          `json:"user_id"`
	CredentialID []byte             `json:"credential_id"`
	PublicKey    []byte             `json:"public_key"`
	Aaguid       []byte             `json:"aaguid"`
	SignCount    int64              `json:"sign_count"`
	Name         string             `json:"name"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type Project struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	Name      string             `json:"name"`
	Color     string             `json:"color"`
	Archived  bool               `json:"archived"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type PublicShare struct {
	ID        uuid.UUID          `json:"id"`
	ReportID  uuid.UUID          `json:"report_id"`
	Slug      string             `json:"slug"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type RecoveryCode struct {
	ID       uuid.UUID `json:"id"`
	UserID   uuid.UUID `json:"user_id"`
	CodeHash string    `json:"code_hash"`
	Used     bool      `json:"used"`
}

type RefreshToken struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	Revoked   bool               `json:"revoked"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Task struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	ProjectID pgtype.UUID        `json:"project_id"`
	Title     string             `json:"title"`
	Type      TaskType           `json:"type"`
	Status    TaskStatus         `json:"status"`
	DueAt     pgtype.Timestamptz `json:"due_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
	MediaUrl  pgtype.Text        `json:"media_url"`
	MediaType pgtype.Text        `json:"media_type"`
	StartAt   pgtype.Timestamptz `json:"start_at"`
}

type TimeBlock struct {
	ID          uuid.UUID          `json:"id"`
	UserID      uuid.UUID          `json:"user_id"`
	TaskID      pgtype.UUID        `json:"task_id"`
	StartedAt   pgtype.Timestamptz `json:"started_at"`
	EndedAt     pgtype.Timestamptz `json:"ended_at"`
	DurationSec pgtype.Int4        `json:"duration_sec"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID                   uuid.UUID          `json:"id"`
	Email                string             `json:"email"`
	PasswordHash         pgtype.Text        `json:"password_hash"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	EmailVerified        bool               `json:"email_verified"`
	EmailVerifyToken     pgtype.Text        `json:"email_verify_token"`
	PasswordResetToken   pgtype.Text        `json:"password_reset_token"`
	PasswordResetExpires pgtype.Timestamptz `json:"password_reset_expires"`
	TotpSecret           pgtype.Text        `json:"totp_secret"`
	TotpEnabled          bool               `json:"totp_enabled"`
}

type WeeklyReport struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	WeekStart pgtype.Date        `json:"week_start"`
	Data      []byte             `json:"data"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}
