// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: passkeys.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createPasskey = `-- name: CreatePasskey :one
INSERT INTO passkeys (user_id, credential_id, public_key, aaguid, sign_count, name)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, credential_id, public_key, aaguid, sign_count, name, created_at
`

type CreatePasskeyParams struct {
	UserID       uuid.UUID `json:"user_id"`
	CredentialID []byte    `json:"credential_id"`
	PublicKey    []byte    `json:"public_key"`
	Aaguid       []byte    `json:"aaguid"`
	SignCount    int64     `json:"sign_count"`
	Name         string    `json:"name"`
}

func (q *Queries) CreatePasskey(ctx context.Context, arg CreatePasskeyParams) (Passkey, error) {
	row := q.db.QueryRow(ctx, createPasskey,
		arg.UserID,
		arg.CredentialID,
		arg.PublicKey,
		arg.Aaguid,
		arg.SignCount,
		arg.Name,
	)
	var i Passkey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CredentialID,
		&i.PublicKey,
		&i.Aaguid,
		&i.SignCount,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const deletePasskey = `-- name: DeletePasskey :exec
DELETE FROM passkeys WHERE id = $1 AND user_id = $2
`

type DeletePasskeyParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeletePasskey(ctx context.Context, arg DeletePasskeyParams) error {
	_, err := q.db.Exec(ctx, deletePasskey, arg.ID, arg.UserID)
	return err
}

const getPasskeyByCredentialID = `-- name: GetPasskeyByCredentialID :one
SELECT id, user_id, credential_id, public_key, aaguid, sign_count, name, created_at FROM passkeys
WHERE credential_id = $1
`

func (q *Queries) GetPasskeyByCredentialID(ctx context.Context, credentialID []byte) (Passkey, error) {
	row := q.db.QueryRow(ctx, getPasskeyByCredentialID, credentialID)
	var i Passkey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CredentialID,
		&i.PublicKey,
		&i.Aaguid,
		&i.SignCount,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const getPasskeysByUserID = `-- name: GetPasskeysByUserID :many
SELECT id, user_id, credential_id, public_key, aaguid, sign_count, name, created_at FROM passkeys
WHERE user_id = $1
ORDER BY created_at
`

func (q *Queries) GetPasskeysByUserID(ctx context.Context, userID uuid.UUID) ([]Passkey, error) {
	rows, err := q.db.Query(ctx, getPasskeysByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Passkey
	for rows.Next() {
		var i Passkey
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CredentialID,
			&i.PublicKey,
			&i.Aaguid,
			&i.SignCount,
			&i.Name,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const renamePasskey = `-- name: RenamePasskey :exec
UPDATE passkeys SET name = $3 WHERE id = $1 AND user_id = $2
`

type RenamePasskeyParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
	Name   string    `json:"name"`
}

func (q *Queries) RenamePasskey(ctx context.Context, arg RenamePasskeyParams) error {
	_, err := q.db.Exec(ctx, renamePasskey, arg.ID, arg.UserID, arg.Name)
	return err
}

const updatePasskeySignCount = `-- name: UpdatePasskeySignCount :exec
UPDATE passkeys SET sign_count = $2 WHERE id = $1
`

type UpdatePasskeySignCountParams struct {
	ID        uuid.UUID `json:"id"`
	SignCount int64     `json:"sign_count"`
}

func (q *Queries) UpdatePasskeySignCount(ctx context.Context, arg UpdatePasskeySignCountParams) error {
	_, err := q.db.Exec(ctx, updatePasskeySignCount, arg.ID, arg.SignCount)
	return err
}
