// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: projects.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createProject = `-- name: CreateProject :one
INSERT INTO projects (user_id, name, color)
VALUES ($1, $2, $3)
RETURNING id, user_id, name, color, archived, created_at
`

type CreateProjectParams struct {
	UserID uuid.UUID `json:"user_id"`
	Name   string    `json:"name"`
	Color  string    `json:"color"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, createProject, arg.UserID, arg.Name, arg.Color)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Color,
		&i.Archived,
		&i.CreatedAt,
	)
	return i, err
}

const deleteProject = `-- name: DeleteProject :one
DELETE FROM projects
WHERE id = $1 AND user_id = $2
RETURNING id
`

type DeleteProjectParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteProject(ctx context.Context, arg DeleteProjectParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, deleteProject, arg.ID, arg.UserID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getProject = `-- name: GetProject :one
SELECT id, user_id, name, color, archived, created_at FROM projects
WHERE id = $1 AND user_id = $2
`

type GetProjectParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetProject(ctx context.Context, arg GetProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, getProject, arg.ID, arg.UserID)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Color,
		&i.Archived,
		&i.CreatedAt,
	)
	return i, err
}

const listProjects = `-- name: ListProjects :many
SELECT id, user_id, name, color, archived, created_at FROM projects
WHERE user_id = $1 AND archived = $2
ORDER BY created_at DESC
`

type ListProjectsParams struct {
	UserID   uuid.UUID `json:"user_id"`
	Archived bool      `json:"archived"`
}

func (q *Queries) ListProjects(ctx context.Context, arg ListProjectsParams) ([]Project, error) {
	rows, err := q.db.Query(ctx, listProjects, arg.UserID, arg.Archived)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Color,
			&i.Archived,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProject = `-- name: UpdateProject :one
UPDATE projects
SET
  name     = COALESCE($1, name),
  color    = COALESCE($2, color),
  archived = COALESCE($3, archived)
WHERE id = $4 AND user_id = $5
RETURNING id, user_id, name, color, archived, created_at
`

type UpdateProjectParams struct {
	Name     pgtype.Text `json:"name"`
	Color    pgtype.Text `json:"color"`
	Archived pgtype.Bool `json:"archived"`
	ID       uuid.UUID   `json:"id"`
	UserID   uuid.UUID   `json:"user_id"`
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, updateProject,
		arg.Name,
		arg.Color,
		arg.Archived,
		arg.ID,
		arg.UserID,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Color,
		&i.Archived,
		&i.CreatedAt,
	)
	return i, err
}
