// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: public_shares.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createPublicShare = `-- name: CreatePublicShare :one
INSERT INTO public_shares (report_id, slug)
VALUES ($1, $2)
RETURNING id, report_id, slug, created_at
`

type CreatePublicShareParams struct {
	ReportID uuid.UUID `json:"report_id"`
	Slug     string    `json:"slug"`
}

func (q *Queries) CreatePublicShare(ctx context.Context, arg CreatePublicShareParams) (PublicShare, error) {
	row := q.db.QueryRow(ctx, createPublicShare, arg.ReportID, arg.Slug)
	var i PublicShare
	err := row.Scan(
		&i.ID,
		&i.ReportID,
		&i.Slug,
		&i.CreatedAt,
	)
	return i, err
}

const deletePublicShareByReportID = `-- name: DeletePublicShareByReportID :exec
DELETE FROM public_shares WHERE report_id = $1
`

func (q *Queries) DeletePublicShareByReportID(ctx context.Context, reportID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deletePublicShareByReportID, reportID)
	return err
}

const getPublicShareByReportID = `-- name: GetPublicShareByReportID :one
SELECT id, report_id, slug, created_at FROM public_shares WHERE report_id = $1
`

func (q *Queries) GetPublicShareByReportID(ctx context.Context, reportID uuid.UUID) (PublicShare, error) {
	row := q.db.QueryRow(ctx, getPublicShareByReportID, reportID)
	var i PublicShare
	err := row.Scan(
		&i.ID,
		&i.ReportID,
		&i.Slug,
		&i.CreatedAt,
	)
	return i, err
}

const getPublicShareBySlug = `-- name: GetPublicShareBySlug :one
SELECT id, report_id, slug, created_at FROM public_shares WHERE slug = $1
`

func (q *Queries) GetPublicShareBySlug(ctx context.Context, slug string) (PublicShare, error) {
	row := q.db.QueryRow(ctx, getPublicShareBySlug, slug)
	var i PublicShare
	err := row.Scan(
		&i.ID,
		&i.ReportID,
		&i.Slug,
		&i.CreatedAt,
	)
	return i, err
}
