// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: retrieval_dismissals.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addRelatedDismissal = `-- name: AddRelatedDismissal :exec
INSERT INTO retrieval_dismissals (user_id, surface, anchor_id, target_id)
VALUES
  ($1, 'related', $2::uuid, $3),
  ($1, 'related', $3, $2::uuid)
ON CONFLICT (user_id, anchor_id, target_id) WHERE surface = 'related'
DO NOTHING
`

type AddRelatedDismissalParams struct {
	UserID   uuid.UUID `json:"user_id"`
	AnchorID uuid.UUID `json:"anchor_id"`
	TargetID uuid.UUID `json:"target_id"`
}

func (q *Queries) AddRelatedDismissal(ctx context.Context, arg AddRelatedDismissalParams) error {
	_, err := q.db.Exec(ctx, addRelatedDismissal, arg.UserID, arg.AnchorID, arg.TargetID)
	return err
}

const addSearchDismissal = `-- name: AddSearchDismissal :exec
INSERT INTO retrieval_dismissals (user_id, surface, query_hash, query_text, target_id)
VALUES (
  $1, 'search', $2,
  $3, $4
)
ON CONFLICT (user_id, query_hash, target_id) WHERE surface = 'search'
DO UPDATE SET created_at = now()
`

type AddSearchDismissalParams struct {
	UserID    uuid.UUID   `json:"user_id"`
	QueryHash []byte      `json:"query_hash"`
	QueryText pgtype.Text `json:"query_text"`
	TargetID  uuid.UUID   `json:"target_id"`
}

func (q *Queries) AddSearchDismissal(ctx context.Context, arg AddSearchDismissalParams) error {
	_, err := q.db.Exec(ctx, addSearchDismissal,
		arg.UserID,
		arg.QueryHash,
		arg.QueryText,
		arg.TargetID,
	)
	return err
}

const listRelatedDismissedIDs = `-- name: ListRelatedDismissedIDs :many
SELECT target_id
FROM retrieval_dismissals
WHERE user_id = $1
  AND surface = 'related'
  AND anchor_id = $2::uuid
ORDER BY created_at, target_id
`

type ListRelatedDismissedIDsParams struct {
	UserID   uuid.UUID `json:"user_id"`
	AnchorID uuid.UUID `json:"anchor_id"`
}

func (q *Queries) ListRelatedDismissedIDs(ctx context.Context, arg ListRelatedDismissedIDsParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listRelatedDismissedIDs, arg.UserID, arg.AnchorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var target_id uuid.UUID
		if err := rows.Scan(&target_id); err != nil {
			return nil, err
		}
		items = append(items, target_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSearchDismissedCaptures = `-- name: ListSearchDismissedCaptures :many
SELECT
  c.id,
  left(COALESCE(NULLIF(c.transcript, ''), c.raw_text, ''), 512)::text AS content,
  c.created_at,
  c.media_type
FROM retrieval_dismissals d
JOIN captures c ON c.id = d.target_id AND c.user_id = d.user_id
WHERE d.user_id = $1
  AND d.surface = 'search'
  AND d.query_hash = $2
  AND c.deleted_at IS NULL
ORDER BY d.created_at, d.target_id
`

type ListSearchDismissedCapturesParams struct {
	UserID    uuid.UUID `json:"user_id"`
	QueryHash []byte    `json:"query_hash"`
}

type ListSearchDismissedCapturesRow struct {
	ID        uuid.UUID          `json:"id"`
	Content   string             `json:"content"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	MediaType CaptureMediaType   `json:"media_type"`
}

// Recovery returns every live preference (the table is retention-bounded), but
// only a bounded preview of each Capture. Restoring uses the ID; the full body
// is neither needed nor safe to materialize here.
func (q *Queries) ListSearchDismissedCaptures(ctx context.Context, arg ListSearchDismissedCapturesParams) ([]ListSearchDismissedCapturesRow, error) {
	rows, err := q.db.Query(ctx, listSearchDismissedCaptures, arg.UserID, arg.QueryHash)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSearchDismissedCapturesRow
	for rows.Next() {
		var i ListSearchDismissedCapturesRow
		if err := rows.Scan(
			&i.ID,
			&i.Content,
			&i.CreatedAt,
			&i.MediaType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSearchDismissedIDs = `-- name: ListSearchDismissedIDs :many
SELECT c.id
FROM retrieval_dismissals d
JOIN captures c ON c.id = d.target_id AND c.user_id = d.user_id
WHERE d.user_id = $1
  AND d.surface = 'search'
  AND d.query_hash = $2
  AND c.deleted_at IS NULL
ORDER BY d.created_at, d.target_id
`

type ListSearchDismissedIDsParams struct {
	UserID    uuid.UUID `json:"user_id"`
	QueryHash []byte    `json:"query_hash"`
}

// The normal search path needs only stable IDs. Keeping content out of this
// query prevents large Capture bodies from amplifying every search request.
func (q *Queries) ListSearchDismissedIDs(ctx context.Context, arg ListSearchDismissedIDsParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listSearchDismissedIDs, arg.UserID, arg.QueryHash)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockSearchDismissals = `-- name: LockSearchDismissals :exec
SELECT pg_advisory_xact_lock(hashtextextended(
  'search-dismissals:' || $1::uuid::text,
  0
))
`

// Serialize a user's feedback mutations so the retention bound is strict even
// when several devices add/remove preferences concurrently.
func (q *Queries) LockSearchDismissals(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, lockSearchDismissals, userID)
	return err
}

const pruneSearchDismissals = `-- name: PruneSearchDismissals :exec
DELETE FROM retrieval_dismissals d
WHERE d.ctid IN (
  SELECT victim.ctid
  FROM retrieval_dismissals victim
  WHERE victim.user_id = $1
    AND victim.surface = 'search'
  ORDER BY victim.created_at DESC, victim.query_hash, victim.target_id
  OFFSET $2
)
`

type PruneSearchDismissalsParams struct {
	UserID    uuid.UUID `json:"user_id"`
	KeepLimit int32     `json:"keep_limit"`
}

// Search feedback is useful recent history, not an unbounded event log. ctid is
// safe here because selection and deletion happen in one statement.
func (q *Queries) PruneSearchDismissals(ctx context.Context, arg PruneSearchDismissalsParams) error {
	_, err := q.db.Exec(ctx, pruneSearchDismissals, arg.UserID, arg.KeepLimit)
	return err
}

const removeRelatedDismissal = `-- name: RemoveRelatedDismissal :exec
DELETE FROM retrieval_dismissals
WHERE user_id = $1
  AND surface = 'related'
  AND (
    (anchor_id = $2::uuid AND target_id = $3)
    OR
    (anchor_id = $3 AND target_id = $2::uuid)
  )
`

type RemoveRelatedDismissalParams struct {
	UserID   uuid.UUID `json:"user_id"`
	AnchorID uuid.UUID `json:"anchor_id"`
	TargetID uuid.UUID `json:"target_id"`
}

func (q *Queries) RemoveRelatedDismissal(ctx context.Context, arg RemoveRelatedDismissalParams) error {
	_, err := q.db.Exec(ctx, removeRelatedDismissal, arg.UserID, arg.AnchorID, arg.TargetID)
	return err
}

const removeSearchDismissal = `-- name: RemoveSearchDismissal :exec
DELETE FROM retrieval_dismissals
WHERE user_id = $1
  AND surface = 'search'
  AND query_hash = $2
  AND target_id = $3
`

type RemoveSearchDismissalParams struct {
	UserID    uuid.UUID `json:"user_id"`
	QueryHash []byte    `json:"query_hash"`
	TargetID  uuid.UUID `json:"target_id"`
}

func (q *Queries) RemoveSearchDismissal(ctx context.Context, arg RemoveSearchDismissalParams) error {
	_, err := q.db.Exec(ctx, removeSearchDismissal, arg.UserID, arg.QueryHash, arg.TargetID)
	return err
}
