// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: review.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const listOnThisDay = `-- name: ListOnThisDay :many
SELECT id, user_id, raw_text, media_url, media_type, created_at, source, transcript, transcription_status, transcription_model, transcription_attempts, transcribed_at, next_transcription_at, audio_duration_sec, media_key, remind_at, deleted_at, remind_hide, todo_at, done_at, link_url FROM captures
WHERE user_id = $1
  AND deleted_at IS NULL
  AND EXTRACT(MONTH FROM created_at) = EXTRACT(MONTH FROM now())
  AND EXTRACT(DAY FROM created_at) = EXTRACT(DAY FROM now())
  AND created_at < date_trunc('day', now())
ORDER BY created_at DESC
LIMIT $2
`

type ListOnThisDayParams struct {
	UserID      uuid.UUID `json:"user_id"`
	ResultLimit int32     `json:"result_limit"`
}

// Captures from the same calendar day (month + day) in an earlier period —
// "on this day" resurfacing. Today's own captures are excluded (created_at is
// before the start of today), so this only surfaces genuinely older memories.
// Month/day and "today" are evaluated in the server clock (UTC), matching how
// the rest of the app stores and compares created_at.
func (q *Queries) ListOnThisDay(ctx context.Context, arg ListOnThisDayParams) ([]Capture, error) {
	rows, err := q.db.Query(ctx, listOnThisDay, arg.UserID, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Capture
	for rows.Next() {
		var i Capture
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.RawText,
			&i.MediaUrl,
			&i.MediaType,
			&i.CreatedAt,
			&i.Source,
			&i.Transcript,
			&i.TranscriptionStatus,
			&i.TranscriptionModel,
			&i.TranscriptionAttempts,
			&i.TranscribedAt,
			&i.NextTranscriptionAt,
			&i.AudioDurationSec,
			&i.MediaKey,
			&i.RemindAt,
			&i.DeletedAt,
			&i.RemindHide,
			&i.TodoAt,
			&i.DoneAt,
			&i.LinkUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRediscover = `-- name: ListRediscover :many
SELECT id, user_id, raw_text, media_url, media_type, created_at, source, transcript, transcription_status, transcription_model, transcription_attempts, transcribed_at, next_transcription_at, audio_duration_sec, media_key, remind_at, deleted_at, remind_hide, todo_at, done_at, link_url FROM captures
WHERE user_id = $1
  AND deleted_at IS NULL
  AND created_at < now() - interval '7 days'
ORDER BY random()
LIMIT $2
`

type ListRediscoverParams struct {
	UserID      uuid.UUID `json:"user_id"`
	ResultLimit int32     `json:"result_limit"`
}

// A random handful of older captures (created more than a week ago) for
// serendipitous recall — this is what keeps the review panel populated when
// "on this day" is sparse in a young library. ORDER BY random() is fine at
// personal scale; this is never a hot path.
func (q *Queries) ListRediscover(ctx context.Context, arg ListRediscoverParams) ([]Capture, error) {
	rows, err := q.db.Query(ctx, listRediscover, arg.UserID, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Capture
	for rows.Next() {
		var i Capture
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.RawText,
			&i.MediaUrl,
			&i.MediaType,
			&i.CreatedAt,
			&i.Source,
			&i.Transcript,
			&i.TranscriptionStatus,
			&i.TranscriptionModel,
			&i.TranscriptionAttempts,
			&i.TranscribedAt,
			&i.NextTranscriptionAt,
			&i.AudioDurationSec,
			&i.MediaKey,
			&i.RemindAt,
			&i.DeletedAt,
			&i.RemindHide,
			&i.TodoAt,
			&i.DoneAt,
			&i.LinkUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
