// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: search.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const searchCaptures = `-- name: SearchCaptures :many
SELECT id, user_id, raw_text, media_url, media_type, classified_as, task_id, created_at FROM captures
WHERE user_id = $1
  AND raw_text IS NOT NULL
  AND raw_text ILIKE '%' || $2::text || '%'
ORDER BY created_at DESC
LIMIT 20
`

type SearchCapturesParams struct {
	UserID uuid.UUID `json:"user_id"`
	Query  string    `json:"query"`
}

func (q *Queries) SearchCaptures(ctx context.Context, arg SearchCapturesParams) ([]Capture, error) {
	rows, err := q.db.Query(ctx, searchCaptures, arg.UserID, arg.Query)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Capture
	for rows.Next() {
		var i Capture
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.RawText,
			&i.MediaUrl,
			&i.MediaType,
			&i.ClassifiedAs,
			&i.TaskID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchLogEntries = `-- name: SearchLogEntries :many
SELECT id, user_id, task_id, body, created_at, deleted_at FROM log_entries
WHERE user_id = $1
  AND deleted_at IS NULL
  AND body ILIKE '%' || $2::text || '%'
ORDER BY created_at DESC
LIMIT 20
`

type SearchLogEntriesParams struct {
	UserID uuid.UUID `json:"user_id"`
	Query  string    `json:"query"`
}

func (q *Queries) SearchLogEntries(ctx context.Context, arg SearchLogEntriesParams) ([]LogEntry, error) {
	rows, err := q.db.Query(ctx, searchLogEntries, arg.UserID, arg.Query)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LogEntry
	for rows.Next() {
		var i LogEntry
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TaskID,
			&i.Body,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchTasks = `-- name: SearchTasks :many
SELECT id, user_id, project_id, title, type, status, due_at, created_at, deleted_at FROM tasks
WHERE user_id = $1
  AND deleted_at IS NULL
  AND title ILIKE '%' || $2::text || '%'
ORDER BY created_at DESC
LIMIT 20
`

type SearchTasksParams struct {
	UserID uuid.UUID `json:"user_id"`
	Query  string    `json:"query"`
}

func (q *Queries) SearchTasks(ctx context.Context, arg SearchTasksParams) ([]Task, error) {
	rows, err := q.db.Query(ctx, searchTasks, arg.UserID, arg.Query)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProjectID,
			&i.Title,
			&i.Type,
			&i.Status,
			&i.DueAt,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
