// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: search.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const searchCaptures = `-- name: SearchCaptures :many
WITH ranked AS (
  SELECT
    captures.id, captures.user_id, captures.raw_text, captures.media_url, captures.media_type, captures.created_at, captures.source, captures.transcript, captures.transcription_status, captures.transcription_model, captures.transcription_attempts, captures.transcribed_at, captures.next_transcription_at, captures.audio_duration_sec, captures.media_key, captures.remind_at, captures.deleted_at, captures.remind_hide, captures.todo_at, captures.done_at,
    CASE
      WHEN raw_text ILIKE '%' || $2::text || '%' THEN 'rawText'
      WHEN transcript ILIKE '%' || $2::text || '%' THEN 'transcript'
      WHEN ts_rank_cd(
        to_tsvector('simple', COALESCE(raw_text, '')),
        websearch_to_tsquery('simple', $2::text)
      ) >= ts_rank_cd(
        to_tsvector('simple', COALESCE(transcript, '')),
        websearch_to_tsquery('simple', $2::text)
      ) THEN 'rawText'
      ELSE 'transcript'
    END AS matched_field,
    (
      CASE
        WHEN raw_text ILIKE '%' || $2::text || '%' THEN 2.0
        WHEN transcript ILIKE '%' || $2::text || '%' THEN 1.8
        ELSE 0.0
      END
      + GREATEST(
          similarity(COALESCE(raw_text, ''), $2::text),
          similarity(COALESCE(transcript, ''), $2::text)
        )
      + ts_rank_cd(
          to_tsvector('simple', COALESCE(raw_text, '') || ' ' || COALESCE(transcript, '')),
          websearch_to_tsquery('simple', $2::text)
        )
    )::double precision AS relevance
  FROM captures
  WHERE user_id = $3
    AND deleted_at IS NULL
    AND (
      raw_text ILIKE '%' || $2::text || '%'
      OR transcript ILIKE '%' || $2::text || '%'
      OR to_tsvector(
        'simple',
        COALESCE(raw_text, '') || ' ' || COALESCE(transcript, '')
      ) @@ websearch_to_tsquery('simple', $2::text)
    )
)
SELECT id, user_id, raw_text, media_url, media_type, created_at, source, transcript, transcription_status, transcription_model, transcription_attempts, transcribed_at, next_transcription_at, audio_duration_sec, media_key, remind_at, deleted_at, remind_hide, todo_at, done_at, matched_field, relevance FROM ranked
ORDER BY relevance DESC, created_at DESC
LIMIT $1
`

type SearchCapturesParams struct {
	ResultLimit int32     `json:"result_limit"`
	Query       string    `json:"query"`
	UserID      uuid.UUID `json:"user_id"`
}

type SearchCapturesRow struct {
	ID                    uuid.UUID           `json:"id"`
	UserID                uuid.UUID           `json:"user_id"`
	RawText               pgtype.Text         `json:"raw_text"`
	MediaUrl              pgtype.Text         `json:"media_url"`
	MediaType             CaptureMediaType    `json:"media_type"`
	CreatedAt             pgtype.Timestamptz  `json:"created_at"`
	Source                string              `json:"source"`
	Transcript            pgtype.Text         `json:"transcript"`
	TranscriptionStatus   TranscriptionStatus `json:"transcription_status"`
	TranscriptionModel    pgtype.Text         `json:"transcription_model"`
	TranscriptionAttempts int32               `json:"transcription_attempts"`
	TranscribedAt         pgtype.Timestamptz  `json:"transcribed_at"`
	NextTranscriptionAt   pgtype.Timestamptz  `json:"next_transcription_at"`
	AudioDurationSec      pgtype.Int4         `json:"audio_duration_sec"`
	MediaKey              pgtype.Text         `json:"media_key"`
	RemindAt              pgtype.Timestamptz  `json:"remind_at"`
	DeletedAt             pgtype.Timestamptz  `json:"deleted_at"`
	RemindHide            bool                `json:"remind_hide"`
	TodoAt                pgtype.Timestamptz  `json:"todo_at"`
	DoneAt                pgtype.Timestamptz  `json:"done_at"`
	MatchedField          string              `json:"matched_field"`
	Relevance             float64             `json:"relevance"`
}

func (q *Queries) SearchCaptures(ctx context.Context, arg SearchCapturesParams) ([]SearchCapturesRow, error) {
	rows, err := q.db.Query(ctx, searchCaptures, arg.ResultLimit, arg.Query, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchCapturesRow
	for rows.Next() {
		var i SearchCapturesRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.RawText,
			&i.MediaUrl,
			&i.MediaType,
			&i.CreatedAt,
			&i.Source,
			&i.Transcript,
			&i.TranscriptionStatus,
			&i.TranscriptionModel,
			&i.TranscriptionAttempts,
			&i.TranscribedAt,
			&i.NextTranscriptionAt,
			&i.AudioDurationSec,
			&i.MediaKey,
			&i.RemindAt,
			&i.DeletedAt,
			&i.RemindHide,
			&i.TodoAt,
			&i.DoneAt,
			&i.MatchedField,
			&i.Relevance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
