// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tasks.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (user_id, project_id, title, type, start_at, due_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, project_id, title, type, status, due_at, created_at, deleted_at, media_url, media_type, start_at
`

type CreateTaskParams struct {
	UserID    uuid.UUID          `json:"user_id"`
	ProjectID pgtype.UUID        `json:"project_id"`
	Title     string             `json:"title"`
	Type      TaskType           `json:"type"`
	StartAt   pgtype.Timestamptz `json:"start_at"`
	DueAt     pgtype.Timestamptz `json:"due_at"`
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, createTask,
		arg.UserID,
		arg.ProjectID,
		arg.Title,
		arg.Type,
		arg.StartAt,
		arg.DueAt,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProjectID,
		&i.Title,
		&i.Type,
		&i.Status,
		&i.DueAt,
		&i.CreatedAt,
		&i.DeletedAt,
		&i.MediaUrl,
		&i.MediaType,
		&i.StartAt,
	)
	return i, err
}

const deleteTask = `-- name: DeleteTask :one
UPDATE tasks
SET deleted_at = now()
WHERE id = $1 AND user_id = $2 AND deleted_at IS NULL
RETURNING id
`

type DeleteTaskParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteTask(ctx context.Context, arg DeleteTaskParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, deleteTask, arg.ID, arg.UserID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getTask = `-- name: GetTask :one
SELECT id, user_id, project_id, title, type, status, due_at, created_at, deleted_at, media_url, media_type, start_at FROM tasks
WHERE id = $1 AND user_id = $2 AND deleted_at IS NULL
`

type GetTaskParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetTask(ctx context.Context, arg GetTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, getTask, arg.ID, arg.UserID)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProjectID,
		&i.Title,
		&i.Type,
		&i.Status,
		&i.DueAt,
		&i.CreatedAt,
		&i.DeletedAt,
		&i.MediaUrl,
		&i.MediaType,
		&i.StartAt,
	)
	return i, err
}

const listTasks = `-- name: ListTasks :many
SELECT id, user_id, project_id, title, type, status, due_at, created_at, deleted_at, media_url, media_type, start_at FROM tasks
WHERE user_id = $1
  AND deleted_at IS NULL
  AND ($2::uuid IS NULL OR project_id = $2::uuid)
  AND ($3::text IS NULL OR status::text = $3::text)
  AND ($4::text IS NULL OR type::text = $4::text)
ORDER BY created_at DESC
`

type ListTasksParams struct {
	UserID    uuid.UUID   `json:"user_id"`
	ProjectID pgtype.UUID `json:"project_id"`
	Status    pgtype.Text `json:"status"`
	Type      pgtype.Text `json:"type"`
}

func (q *Queries) ListTasks(ctx context.Context, arg ListTasksParams) ([]Task, error) {
	rows, err := q.db.Query(ctx, listTasks,
		arg.UserID,
		arg.ProjectID,
		arg.Status,
		arg.Type,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProjectID,
			&i.Title,
			&i.Type,
			&i.Status,
			&i.DueAt,
			&i.CreatedAt,
			&i.DeletedAt,
			&i.MediaUrl,
			&i.MediaType,
			&i.StartAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksInRange = `-- name: ListTasksInRange :many
SELECT id, user_id, project_id, title, type, status, due_at, created_at, deleted_at, media_url, media_type, start_at FROM tasks
WHERE user_id = $1
  AND deleted_at IS NULL
  AND created_at >= $2
  AND created_at < $3
ORDER BY created_at
`

type ListTasksInRangeParams struct {
	UserID      uuid.UUID          `json:"user_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	CreatedAt_2 pgtype.Timestamptz `json:"created_at_2"`
}

func (q *Queries) ListTasksInRange(ctx context.Context, arg ListTasksInRangeParams) ([]Task, error) {
	rows, err := q.db.Query(ctx, listTasksInRange, arg.UserID, arg.CreatedAt, arg.CreatedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProjectID,
			&i.Title,
			&i.Type,
			&i.Status,
			&i.DueAt,
			&i.CreatedAt,
			&i.DeletedAt,
			&i.MediaUrl,
			&i.MediaType,
			&i.StartAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTask = `-- name: UpdateTask :one
UPDATE tasks
SET
  title      = COALESCE($1, title),
  status     = CASE WHEN $2::text IS NOT NULL
               THEN $2::task_status
               ELSE status END,
  type       = CASE WHEN $3::text IS NOT NULL
               THEN $3::task_type
               ELSE type END,
  project_id = COALESCE($4::uuid, project_id),
  start_at   = CASE WHEN $5::boolean
               THEN NULL
               ELSE COALESCE($6::timestamptz, start_at) END,
  due_at     = CASE WHEN $7::boolean
               THEN NULL
               ELSE COALESCE($8::timestamptz, due_at) END,
  media_url  = COALESCE($9, media_url),
  media_type = COALESCE($10, media_type)
WHERE id = $11 AND user_id = $12 AND deleted_at IS NULL
RETURNING id, user_id, project_id, title, type, status, due_at, created_at, deleted_at, media_url, media_type, start_at
`

type UpdateTaskParams struct {
	Title        pgtype.Text        `json:"title"`
	Status       pgtype.Text        `json:"status"`
	Type         pgtype.Text        `json:"type"`
	ProjectID    pgtype.UUID        `json:"project_id"`
	ClearStartAt bool               `json:"clear_start_at"`
	StartAt      pgtype.Timestamptz `json:"start_at"`
	ClearDueAt   bool               `json:"clear_due_at"`
	DueAt        pgtype.Timestamptz `json:"due_at"`
	MediaUrl     pgtype.Text        `json:"media_url"`
	MediaType    pgtype.Text        `json:"media_type"`
	ID           uuid.UUID          `json:"id"`
	UserID       uuid.UUID          `json:"user_id"`
}

func (q *Queries) UpdateTask(ctx context.Context, arg UpdateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, updateTask,
		arg.Title,
		arg.Status,
		arg.Type,
		arg.ProjectID,
		arg.ClearStartAt,
		arg.StartAt,
		arg.ClearDueAt,
		arg.DueAt,
		arg.MediaUrl,
		arg.MediaType,
		arg.ID,
		arg.UserID,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProjectID,
		&i.Title,
		&i.Type,
		&i.Status,
		&i.DueAt,
		&i.CreatedAt,
		&i.DeletedAt,
		&i.MediaUrl,
		&i.MediaType,
		&i.StartAt,
	)
	return i, err
}
