// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: time_blocks.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createTimeBlock = `-- name: CreateTimeBlock :one
INSERT INTO time_blocks (user_id, task_id, started_at, ended_at, duration_sec)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, task_id, started_at, ended_at, duration_sec, created_at
`

type CreateTimeBlockParams struct {
	UserID      uuid.UUID          `json:"user_id"`
	TaskID      pgtype.UUID        `json:"task_id"`
	StartedAt   pgtype.Timestamptz `json:"started_at"`
	EndedAt     pgtype.Timestamptz `json:"ended_at"`
	DurationSec pgtype.Int4        `json:"duration_sec"`
}

func (q *Queries) CreateTimeBlock(ctx context.Context, arg CreateTimeBlockParams) (TimeBlock, error) {
	row := q.db.QueryRow(ctx, createTimeBlock,
		arg.UserID,
		arg.TaskID,
		arg.StartedAt,
		arg.EndedAt,
		arg.DurationSec,
	)
	var i TimeBlock
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TaskID,
		&i.StartedAt,
		&i.EndedAt,
		&i.DurationSec,
		&i.CreatedAt,
	)
	return i, err
}

const deleteTimeBlock = `-- name: DeleteTimeBlock :one
DELETE FROM time_blocks
WHERE id = $1 AND user_id = $2
RETURNING id
`

type DeleteTimeBlockParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteTimeBlock(ctx context.Context, arg DeleteTimeBlockParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, deleteTimeBlock, arg.ID, arg.UserID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const listTimeBlocks = `-- name: ListTimeBlocks :many
SELECT id, user_id, task_id, started_at, ended_at, duration_sec, created_at FROM time_blocks
WHERE user_id = $1
  AND ($2::uuid IS NULL OR task_id = $2::uuid)
ORDER BY started_at DESC
`

type ListTimeBlocksParams struct {
	UserID uuid.UUID   `json:"user_id"`
	TaskID pgtype.UUID `json:"task_id"`
}

func (q *Queries) ListTimeBlocks(ctx context.Context, arg ListTimeBlocksParams) ([]TimeBlock, error) {
	rows, err := q.db.Query(ctx, listTimeBlocks, arg.UserID, arg.TaskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TimeBlock
	for rows.Next() {
		var i TimeBlock
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TaskID,
			&i.StartedAt,
			&i.EndedAt,
			&i.DurationSec,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTimeBlocksInRange = `-- name: ListTimeBlocksInRange :many
SELECT id, user_id, task_id, started_at, ended_at, duration_sec, created_at FROM time_blocks
WHERE user_id = $1
  AND started_at >= $2
  AND started_at < $3
ORDER BY started_at
`

type ListTimeBlocksInRangeParams struct {
	UserID      uuid.UUID          `json:"user_id"`
	StartedAt   pgtype.Timestamptz `json:"started_at"`
	StartedAt_2 pgtype.Timestamptz `json:"started_at_2"`
}

func (q *Queries) ListTimeBlocksInRange(ctx context.Context, arg ListTimeBlocksInRangeParams) ([]TimeBlock, error) {
	rows, err := q.db.Query(ctx, listTimeBlocksInRange, arg.UserID, arg.StartedAt, arg.StartedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TimeBlock
	for rows.Next() {
		var i TimeBlock
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TaskID,
			&i.StartedAt,
			&i.EndedAt,
			&i.DurationSec,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTimeBlock = `-- name: UpdateTimeBlock :one
UPDATE time_blocks
SET
  task_id      = COALESCE($1::uuid,       task_id),
  started_at   = COALESCE($2::timestamptz, started_at),
  ended_at     = COALESCE($3::timestamptz,   ended_at),
  duration_sec = COALESCE($4::integer,   duration_sec)
WHERE id = $5 AND user_id = $6
RETURNING id, user_id, task_id, started_at, ended_at, duration_sec, created_at
`

type UpdateTimeBlockParams struct {
	TaskID      pgtype.UUID        `json:"task_id"`
	StartedAt   pgtype.Timestamptz `json:"started_at"`
	EndedAt     pgtype.Timestamptz `json:"ended_at"`
	DurationSec pgtype.Int4        `json:"duration_sec"`
	ID          uuid.UUID          `json:"id"`
	UserID      uuid.UUID          `json:"user_id"`
}

func (q *Queries) UpdateTimeBlock(ctx context.Context, arg UpdateTimeBlockParams) (TimeBlock, error) {
	row := q.db.QueryRow(ctx, updateTimeBlock,
		arg.TaskID,
		arg.StartedAt,
		arg.EndedAt,
		arg.DurationSec,
		arg.ID,
		arg.UserID,
	)
	var i TimeBlock
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TaskID,
		&i.StartedAt,
		&i.EndedAt,
		&i.DurationSec,
		&i.CreatedAt,
	)
	return i, err
}
