// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: totp.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createRecoveryCode = `-- name: CreateRecoveryCode :exec
INSERT INTO recovery_codes (user_id, code_hash) VALUES ($1, $2)
`

type CreateRecoveryCodeParams struct {
	UserID   uuid.UUID `json:"user_id"`
	CodeHash string    `json:"code_hash"`
}

func (q *Queries) CreateRecoveryCode(ctx context.Context, arg CreateRecoveryCodeParams) error {
	_, err := q.db.Exec(ctx, createRecoveryCode, arg.UserID, arg.CodeHash)
	return err
}

const deleteRecoveryCodes = `-- name: DeleteRecoveryCodes :exec
DELETE FROM recovery_codes WHERE user_id = $1
`

func (q *Queries) DeleteRecoveryCodes(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteRecoveryCodes, userID)
	return err
}

const disableTOTP = `-- name: DisableTOTP :exec
UPDATE users SET totp_enabled = false, totp_secret = NULL WHERE id = $1
`

func (q *Queries) DisableTOTP(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, disableTOTP, id)
	return err
}

const enableTOTP = `-- name: EnableTOTP :exec
UPDATE users SET totp_enabled = true WHERE id = $1
`

func (q *Queries) EnableTOTP(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, enableTOTP, id)
	return err
}

const getRecoveryCodes = `-- name: GetRecoveryCodes :many
SELECT id, user_id, code_hash, used FROM recovery_codes WHERE user_id = $1
`

func (q *Queries) GetRecoveryCodes(ctx context.Context, userID uuid.UUID) ([]RecoveryCode, error) {
	rows, err := q.db.Query(ctx, getRecoveryCodes, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RecoveryCode
	for rows.Next() {
		var i RecoveryCode
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CodeHash,
			&i.Used,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setTOTPSecret = `-- name: SetTOTPSecret :exec
UPDATE users SET totp_secret = $2 WHERE id = $1
`

type SetTOTPSecretParams struct {
	ID         uuid.UUID   `json:"id"`
	TotpSecret pgtype.Text `json:"totp_secret"`
}

func (q *Queries) SetTOTPSecret(ctx context.Context, arg SetTOTPSecretParams) error {
	_, err := q.db.Exec(ctx, setTOTPSecret, arg.ID, arg.TotpSecret)
	return err
}

const useRecoveryCode = `-- name: UseRecoveryCode :exec
UPDATE recovery_codes SET used = true WHERE id = $1
`

func (q *Queries) UseRecoveryCode(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, useRecoveryCode, id)
	return err
}
