// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: upload_operations.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const completeCaptureUploadOperation = `-- name: CompleteCaptureUploadOperation :execrows
UPDATE capture_upload_operations
SET completed_at = now(), lease_until = now()
WHERE id = $1::uuid
  AND user_id = $2::uuid
  AND request_hash = $3::text
  AND completed_at IS NULL
`

type CompleteCaptureUploadOperationParams struct {
	ID          uuid.UUID `json:"id"`
	UserID      uuid.UUID `json:"user_id"`
	RequestHash string    `json:"request_hash"`
}

func (q *Queries) CompleteCaptureUploadOperation(ctx context.Context, arg CompleteCaptureUploadOperationParams) (int64, error) {
	result, err := q.db.Exec(ctx, completeCaptureUploadOperation, arg.ID, arg.UserID, arg.RequestHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCaptureUploadOperation = `-- name: GetCaptureUploadOperation :one
SELECT id, capture_id, user_id, request_hash, lease_until, completed_at, created_at FROM capture_upload_operations
WHERE id = $1::uuid
`

func (q *Queries) GetCaptureUploadOperation(ctx context.Context, id uuid.UUID) (CaptureUploadOperation, error) {
	row := q.db.QueryRow(ctx, getCaptureUploadOperation, id)
	var i CaptureUploadOperation
	err := row.Scan(
		&i.ID,
		&i.CaptureID,
		&i.UserID,
		&i.RequestHash,
		&i.LeaseUntil,
		&i.CompletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const releaseCaptureUploadOperation = `-- name: ReleaseCaptureUploadOperation :execrows
UPDATE capture_upload_operations
SET lease_until = now()
WHERE id = $1::uuid
  AND user_id = $2::uuid
  AND request_hash = $3::text
  AND completed_at IS NULL
`

type ReleaseCaptureUploadOperationParams struct {
	ID          uuid.UUID `json:"id"`
	UserID      uuid.UUID `json:"user_id"`
	RequestHash string    `json:"request_hash"`
}

func (q *Queries) ReleaseCaptureUploadOperation(ctx context.Context, arg ReleaseCaptureUploadOperationParams) (int64, error) {
	result, err := q.db.Exec(ctx, releaseCaptureUploadOperation, arg.ID, arg.UserID, arg.RequestHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const reserveCaptureUploadOperation = `-- name: ReserveCaptureUploadOperation :one
INSERT INTO capture_upload_operations (
  id, capture_id, user_id, request_hash, lease_until
) SELECT
  $1::uuid,
  $2::uuid,
  $3::uuid,
  $4::text,
  now() + interval '1 minute'
WHERE NOT EXISTS (
  SELECT 1 FROM captures WHERE captures.id = $2::uuid
)
ON CONFLICT (id) DO UPDATE
SET lease_until = now() + interval '1 minute'
WHERE capture_upload_operations.user_id = excluded.user_id
  AND capture_upload_operations.request_hash = excluded.request_hash
  AND capture_upload_operations.completed_at IS NULL
  AND capture_upload_operations.lease_until <= now()
RETURNING id, capture_id, user_id, request_hash, lease_until, completed_at, created_at
`

type ReserveCaptureUploadOperationParams struct {
	ID          uuid.UUID `json:"id"`
	CaptureID   uuid.UUID `json:"capture_id"`
	UserID      uuid.UUID `json:"user_id"`
	RequestHash string    `json:"request_hash"`
}

func (q *Queries) ReserveCaptureUploadOperation(ctx context.Context, arg ReserveCaptureUploadOperationParams) (CaptureUploadOperation, error) {
	row := q.db.QueryRow(ctx, reserveCaptureUploadOperation,
		arg.ID,
		arg.CaptureID,
		arg.UserID,
		arg.RequestHash,
	)
	var i CaptureUploadOperation
	err := row.Scan(
		&i.ID,
		&i.CaptureID,
		&i.UserID,
		&i.RequestHash,
		&i.LeaseUntil,
		&i.CompletedAt,
		&i.CreatedAt,
	)
	return i, err
}
