// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: webhooks.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createWebhook = `-- name: CreateWebhook :one
INSERT INTO capture_webhooks (
  user_id, name, target_url, keywords, semantic_query, semantic_threshold,
  payload_template, enabled
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, user_id, name, target_url, keywords, semantic_query, semantic_threshold, payload_template, enabled, created_at, deleted_at
`

type CreateWebhookParams struct {
	UserID            uuid.UUID   `json:"user_id"`
	Name              string      `json:"name"`
	TargetUrl         string      `json:"target_url"`
	Keywords          []string    `json:"keywords"`
	SemanticQuery     pgtype.Text `json:"semantic_query"`
	SemanticThreshold float64     `json:"semantic_threshold"`
	PayloadTemplate   string      `json:"payload_template"`
	Enabled           bool        `json:"enabled"`
}

func (q *Queries) CreateWebhook(ctx context.Context, arg CreateWebhookParams) (CaptureWebhook, error) {
	row := q.db.QueryRow(ctx, createWebhook,
		arg.UserID,
		arg.Name,
		arg.TargetUrl,
		arg.Keywords,
		arg.SemanticQuery,
		arg.SemanticThreshold,
		arg.PayloadTemplate,
		arg.Enabled,
	)
	var i CaptureWebhook
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.TargetUrl,
		&i.Keywords,
		&i.SemanticQuery,
		&i.SemanticThreshold,
		&i.PayloadTemplate,
		&i.Enabled,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getWebhook = `-- name: GetWebhook :one
SELECT id, user_id, name, target_url, keywords, semantic_query, semantic_threshold, payload_template, enabled, created_at, deleted_at FROM capture_webhooks
WHERE id = $1 AND user_id = $2 AND deleted_at IS NULL
`

type GetWebhookParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetWebhook(ctx context.Context, arg GetWebhookParams) (CaptureWebhook, error) {
	row := q.db.QueryRow(ctx, getWebhook, arg.ID, arg.UserID)
	var i CaptureWebhook
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.TargetUrl,
		&i.Keywords,
		&i.SemanticQuery,
		&i.SemanticThreshold,
		&i.PayloadTemplate,
		&i.Enabled,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listWebhooks = `-- name: ListWebhooks :many
SELECT id, user_id, name, target_url, keywords, semantic_query, semantic_threshold, payload_template, enabled, created_at, deleted_at FROM capture_webhooks
WHERE user_id = $1 AND deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListWebhooks(ctx context.Context, userID uuid.UUID) ([]CaptureWebhook, error) {
	rows, err := q.db.Query(ctx, listWebhooks, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CaptureWebhook
	for rows.Next() {
		var i CaptureWebhook
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.TargetUrl,
			&i.Keywords,
			&i.SemanticQuery,
			&i.SemanticThreshold,
			&i.PayloadTemplate,
			&i.Enabled,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteWebhook = `-- name: SoftDeleteWebhook :one
UPDATE capture_webhooks
SET deleted_at = now()
WHERE id = $1 AND user_id = $2 AND deleted_at IS NULL
RETURNING id
`

type SoftDeleteWebhookParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) SoftDeleteWebhook(ctx context.Context, arg SoftDeleteWebhookParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, softDeleteWebhook, arg.ID, arg.UserID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const updateWebhook = `-- name: UpdateWebhook :one
UPDATE capture_webhooks
SET name               = $3,
    target_url         = $4,
    keywords           = $5,
    semantic_query     = $6,
    semantic_threshold = $7,
    payload_template   = $8,
    enabled            = $9
WHERE id = $1 AND user_id = $2 AND deleted_at IS NULL
RETURNING id, user_id, name, target_url, keywords, semantic_query, semantic_threshold, payload_template, enabled, created_at, deleted_at
`

type UpdateWebhookParams struct {
	ID                uuid.UUID   `json:"id"`
	UserID            uuid.UUID   `json:"user_id"`
	Name              string      `json:"name"`
	TargetUrl         string      `json:"target_url"`
	Keywords          []string    `json:"keywords"`
	SemanticQuery     pgtype.Text `json:"semantic_query"`
	SemanticThreshold float64     `json:"semantic_threshold"`
	PayloadTemplate   string      `json:"payload_template"`
	Enabled           bool        `json:"enabled"`
}

func (q *Queries) UpdateWebhook(ctx context.Context, arg UpdateWebhookParams) (CaptureWebhook, error) {
	row := q.db.QueryRow(ctx, updateWebhook,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.TargetUrl,
		arg.Keywords,
		arg.SemanticQuery,
		arg.SemanticThreshold,
		arg.PayloadTemplate,
		arg.Enabled,
	)
	var i CaptureWebhook
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.TargetUrl,
		&i.Keywords,
		&i.SemanticQuery,
		&i.SemanticThreshold,
		&i.PayloadTemplate,
		&i.Enabled,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}
