// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: weekly_reports.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getWeeklyReport = `-- name: GetWeeklyReport :one
SELECT id, user_id, week_start, data, created_at FROM weekly_reports
WHERE id = $1 AND user_id = $2
`

type GetWeeklyReportParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetWeeklyReport(ctx context.Context, arg GetWeeklyReportParams) (WeeklyReport, error) {
	row := q.db.QueryRow(ctx, getWeeklyReport, arg.ID, arg.UserID)
	var i WeeklyReport
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.WeekStart,
		&i.Data,
		&i.CreatedAt,
	)
	return i, err
}

const getWeeklyReportBySlug = `-- name: GetWeeklyReportBySlug :one
SELECT wr.id, wr.user_id, wr.week_start, wr.data, wr.created_at FROM weekly_reports wr
JOIN public_shares ps ON ps.report_id = wr.id
WHERE ps.slug = $1
`

func (q *Queries) GetWeeklyReportBySlug(ctx context.Context, slug string) (WeeklyReport, error) {
	row := q.db.QueryRow(ctx, getWeeklyReportBySlug, slug)
	var i WeeklyReport
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.WeekStart,
		&i.Data,
		&i.CreatedAt,
	)
	return i, err
}

const listWeeklyReports = `-- name: ListWeeklyReports :many
SELECT id, user_id, week_start, data, created_at FROM weekly_reports
WHERE user_id = $1
ORDER BY week_start DESC
`

func (q *Queries) ListWeeklyReports(ctx context.Context, userID uuid.UUID) ([]WeeklyReport, error) {
	rows, err := q.db.Query(ctx, listWeeklyReports, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WeeklyReport
	for rows.Next() {
		var i WeeklyReport
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.WeekStart,
			&i.Data,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertWeeklyReport = `-- name: UpsertWeeklyReport :one
INSERT INTO weekly_reports (user_id, week_start, data)
VALUES ($1, $2, $3)
ON CONFLICT (user_id, week_start)
DO UPDATE SET data = $3
RETURNING id, user_id, week_start, data, created_at
`

type UpsertWeeklyReportParams struct {
	UserID    uuid.UUID   `json:"user_id"`
	WeekStart pgtype.Date `json:"week_start"`
	Data      []byte      `json:"data"`
}

func (q *Queries) UpsertWeeklyReport(ctx context.Context, arg UpsertWeeklyReportParams) (WeeklyReport, error) {
	row := q.db.QueryRow(ctx, upsertWeeklyReport, arg.UserID, arg.WeekStart, arg.Data)
	var i WeeklyReport
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.WeekStart,
		&i.Data,
		&i.CreatedAt,
	)
	return i, err
}
